/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Member from '../model/Member';
import Members from '../model/Members';

/**
* Member service.
* @module api/MemberApi
* @version 1.0.0
*/
export default class MemberApi {

    /**
    * Constructs a new MemberApi. 
    * @alias module:api/MemberApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * get members
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Members} and HTTP response
     */
    memberGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Members;
      return this.apiClient.callApi(
        '/member', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * get members
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Members}
     */
    memberGet() {
      return this.memberGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * delete member
     * @param {Number} memberId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Member} and HTTP response
     */
    memberMemberIdDeleteWithHttpInfo(memberId) {
      let postBody = null;
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling memberMemberIdDelete");
      }

      let pathParams = {
        'member_id': memberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Member;
      return this.apiClient.callApi(
        '/member/{member_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * delete member
     * @param {Number} memberId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Member}
     */
    memberMemberIdDelete(memberId) {
      return this.memberMemberIdDeleteWithHttpInfo(memberId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * patch member
     * @param {Number} memberId 
     * @param {Object} opts Optional parameters
     * @param {String} [memberName] 
     * @param {String} [memberIntro] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Member} and HTTP response
     */
    memberMemberIdPatchWithHttpInfo(memberId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling memberMemberIdPatch");
      }

      let pathParams = {
        'member_id': memberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'member_name': opts['memberName'],
        'member_intro': opts['memberIntro']
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Member;
      return this.apiClient.callApi(
        '/member/{member_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * patch member
     * @param {Number} memberId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.memberName 
     * @param {String} opts.memberIntro 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Member}
     */
    memberMemberIdPatch(memberId, opts) {
      return this.memberMemberIdPatchWithHttpInfo(memberId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * put member
     * @param {Number} memberId 
     * @param {String} memberName 
     * @param {String} memberIntro 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Member} and HTTP response
     */
    memberMemberIdPutWithHttpInfo(memberId, memberName, memberIntro) {
      let postBody = null;
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling memberMemberIdPut");
      }
      // verify the required parameter 'memberName' is set
      if (memberName === undefined || memberName === null) {
        throw new Error("Missing the required parameter 'memberName' when calling memberMemberIdPut");
      }
      // verify the required parameter 'memberIntro' is set
      if (memberIntro === undefined || memberIntro === null) {
        throw new Error("Missing the required parameter 'memberIntro' when calling memberMemberIdPut");
      }

      let pathParams = {
        'member_id': memberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'member_name': memberName,
        'member_intro': memberIntro
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Member;
      return this.apiClient.callApi(
        '/member/{member_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * put member
     * @param {Number} memberId 
     * @param {String} memberName 
     * @param {String} memberIntro 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Member}
     */
    memberMemberIdPut(memberId, memberName, memberIntro) {
      return this.memberMemberIdPutWithHttpInfo(memberId, memberName, memberIntro)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * post member
     * @param {String} memberName 
     * @param {String} memberIntro 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Member} and HTTP response
     */
    memberPostWithHttpInfo(memberName, memberIntro) {
      let postBody = null;
      // verify the required parameter 'memberName' is set
      if (memberName === undefined || memberName === null) {
        throw new Error("Missing the required parameter 'memberName' when calling memberPost");
      }
      // verify the required parameter 'memberIntro' is set
      if (memberIntro === undefined || memberIntro === null) {
        throw new Error("Missing the required parameter 'memberIntro' when calling memberPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'member_name': memberName,
        'member_intro': memberIntro
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Member;
      return this.apiClient.callApi(
        '/member', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * post member
     * @param {String} memberName 
     * @param {String} memberIntro 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Member}
     */
    memberPost(memberName, memberIntro) {
      return this.memberPostWithHttpInfo(memberName, memberIntro)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
