/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.MemberResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberResponse', function() {
    it('should create an instance of MemberResponse', function() {
      // uncomment below and update the code to test MemberResponse
      //var instance = new WidmBackEnd.MemberResponse();
      //expect(instance).to.be.a(WidmBackEnd.MemberResponse);
    });

    it('should have the property createTime (base name: "create_time")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new WidmBackEnd.MemberResponse();
      //expect(instance).to.be();
    });

    it('should have the property memberIntro (base name: "member_intro")', function() {
      // uncomment below and update the code to test the property memberIntro
      //var instance = new WidmBackEnd.MemberResponse();
      //expect(instance).to.be();
    });

    it('should have the property memberName (base name: "member_name")', function() {
      // uncomment below and update the code to test the property memberName
      //var instance = new WidmBackEnd.MemberResponse();
      //expect(instance).to.be();
    });

    it('should have the property updateTime (base name: "update_time")', function() {
      // uncomment below and update the code to test the property updateTime
      //var instance = new WidmBackEnd.MemberResponse();
      //expect(instance).to.be();
    });

  });

}));
