/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.ProjectTaskApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectTaskApi', function() {
    describe('projectProjectIdTaskGet', function() {
      it('should call projectProjectIdTaskGet successfully', function(done) {
        //uncomment below and update the code to test projectProjectIdTaskGet
        //instance.projectProjectIdTaskGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectProjectIdTaskPost', function() {
      it('should call projectProjectIdTaskPost successfully', function(done) {
        //uncomment below and update the code to test projectProjectIdTaskPost
        //instance.projectProjectIdTaskPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectProjectIdTaskProjectTaskIdDelete', function() {
      it('should call projectProjectIdTaskProjectTaskIdDelete successfully', function(done) {
        //uncomment below and update the code to test projectProjectIdTaskProjectTaskIdDelete
        //instance.projectProjectIdTaskProjectTaskIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectProjectIdTaskProjectTaskIdGet', function() {
      it('should call projectProjectIdTaskProjectTaskIdGet successfully', function(done) {
        //uncomment below and update the code to test projectProjectIdTaskProjectTaskIdGet
        //instance.projectProjectIdTaskProjectTaskIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('projectProjectIdTaskProjectTaskIdPatch', function() {
      it('should call projectProjectIdTaskProjectTaskIdPatch successfully', function(done) {
        //uncomment below and update the code to test projectProjectIdTaskProjectTaskIdPatch
        //instance.projectProjectIdTaskProjectTaskIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
