/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActivityResponse model module.
 * @module model/ActivityResponse
 * @version 1.0.0
 */
class ActivityResponse {
    /**
     * Constructs a new <code>ActivityResponse</code>.
     * @alias module:model/ActivityResponse
     */
    constructor() { 
        
        ActivityResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActivityResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActivityResponse} obj Optional instance to populate.
     * @return {module:model/ActivityResponse} The populated <code>ActivityResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivityResponse();

            if (data.hasOwnProperty('activity_sub_title')) {
                obj['activity_sub_title'] = ApiClient.convertToType(data['activity_sub_title'], 'String');
            }
            if (data.hasOwnProperty('activity_title')) {
                obj['activity_title'] = ApiClient.convertToType(data['activity_title'], 'String');
            }
            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('update_time')) {
                obj['update_time'] = ApiClient.convertToType(data['update_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActivityResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActivityResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['activity_sub_title'] && !(typeof data['activity_sub_title'] === 'string' || data['activity_sub_title'] instanceof String)) {
            throw new Error("Expected the field `activity_sub_title` to be a primitive type in the JSON string but got " + data['activity_sub_title']);
        }
        // ensure the json data is a string
        if (data['activity_title'] && !(typeof data['activity_title'] === 'string' || data['activity_title'] instanceof String)) {
            throw new Error("Expected the field `activity_title` to be a primitive type in the JSON string but got " + data['activity_title']);
        }
        // ensure the json data is a string
        if (data['create_time'] && !(typeof data['create_time'] === 'string' || data['create_time'] instanceof String)) {
            throw new Error("Expected the field `create_time` to be a primitive type in the JSON string but got " + data['create_time']);
        }
        // ensure the json data is a string
        if (data['update_time'] && !(typeof data['update_time'] === 'string' || data['update_time'] instanceof String)) {
            throw new Error("Expected the field `update_time` to be a primitive type in the JSON string but got " + data['update_time']);
        }

        return true;
    }


}



/**
 * @member {String} activity_sub_title
 */
ActivityResponse.prototype['activity_sub_title'] = undefined;

/**
 * @member {String} activity_title
 */
ActivityResponse.prototype['activity_title'] = undefined;

/**
 * @member {String} create_time
 */
ActivityResponse.prototype['create_time'] = undefined;

/**
 * @member {Number} id
 */
ActivityResponse.prototype['id'] = undefined;

/**
 * @member {String} update_time
 */
ActivityResponse.prototype['update_time'] = undefined;






export default ActivityResponse;

