/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewsImageResponse model module.
 * @module model/NewsImageResponse
 * @version 1.0.0
 */
class NewsImageResponse {
    /**
     * Constructs a new <code>NewsImageResponse</code>.
     * @alias module:model/NewsImageResponse
     */
    constructor() { 
        
        NewsImageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewsImageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewsImageResponse} obj Optional instance to populate.
     * @return {module:model/NewsImageResponse} The populated <code>NewsImageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewsImageResponse();

            if (data.hasOwnProperty('created_time')) {
                obj['created_time'] = ApiClient.convertToType(data['created_time'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('image_name')) {
                obj['image_name'] = ApiClient.convertToType(data['image_name'], 'String');
            }
            if (data.hasOwnProperty('image_path')) {
                obj['image_path'] = ApiClient.convertToType(data['image_path'], 'String');
            }
            if (data.hasOwnProperty('image_uuid')) {
                obj['image_uuid'] = ApiClient.convertToType(data['image_uuid'], 'String');
            }
            if (data.hasOwnProperty('updated_time')) {
                obj['updated_time'] = ApiClient.convertToType(data['updated_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewsImageResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewsImageResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_time'] && !(typeof data['created_time'] === 'string' || data['created_time'] instanceof String)) {
            throw new Error("Expected the field `created_time` to be a primitive type in the JSON string but got " + data['created_time']);
        }
        // ensure the json data is a string
        if (data['image_name'] && !(typeof data['image_name'] === 'string' || data['image_name'] instanceof String)) {
            throw new Error("Expected the field `image_name` to be a primitive type in the JSON string but got " + data['image_name']);
        }
        // ensure the json data is a string
        if (data['image_path'] && !(typeof data['image_path'] === 'string' || data['image_path'] instanceof String)) {
            throw new Error("Expected the field `image_path` to be a primitive type in the JSON string but got " + data['image_path']);
        }
        // ensure the json data is a string
        if (data['image_uuid'] && !(typeof data['image_uuid'] === 'string' || data['image_uuid'] instanceof String)) {
            throw new Error("Expected the field `image_uuid` to be a primitive type in the JSON string but got " + data['image_uuid']);
        }
        // ensure the json data is a string
        if (data['updated_time'] && !(typeof data['updated_time'] === 'string' || data['updated_time'] instanceof String)) {
            throw new Error("Expected the field `updated_time` to be a primitive type in the JSON string but got " + data['updated_time']);
        }

        return true;
    }


}



/**
 * @member {String} created_time
 */
NewsImageResponse.prototype['created_time'] = undefined;

/**
 * @member {Number} id
 */
NewsImageResponse.prototype['id'] = undefined;

/**
 * @member {String} image_name
 */
NewsImageResponse.prototype['image_name'] = undefined;

/**
 * @member {String} image_path
 */
NewsImageResponse.prototype['image_path'] = undefined;

/**
 * @member {String} image_uuid
 */
NewsImageResponse.prototype['image_uuid'] = undefined;

/**
 * @member {String} updated_time
 */
NewsImageResponse.prototype['updated_time'] = undefined;






export default NewsImageResponse;

