/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewsesResponseInner model module.
 * @module model/NewsesResponseInner
 * @version 1.0.0
 */
class NewsesResponseInner {
    /**
     * Constructs a new <code>NewsesResponseInner</code>.
     * @alias module:model/NewsesResponseInner
     */
    constructor() { 
        
        NewsesResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewsesResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewsesResponseInner} obj Optional instance to populate.
     * @return {module:model/NewsesResponseInner} The populated <code>NewsesResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewsesResponseInner();

            if (data.hasOwnProperty('created_time')) {
                obj['created_time'] = ApiClient.convertToType(data['created_time'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('news_content')) {
                obj['news_content'] = ApiClient.convertToType(data['news_content'], 'String');
            }
            if (data.hasOwnProperty('news_sub_title')) {
                obj['news_sub_title'] = ApiClient.convertToType(data['news_sub_title'], 'String');
            }
            if (data.hasOwnProperty('news_title')) {
                obj['news_title'] = ApiClient.convertToType(data['news_title'], 'String');
            }
            if (data.hasOwnProperty('updated_time')) {
                obj['updated_time'] = ApiClient.convertToType(data['updated_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewsesResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewsesResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_time'] && !(typeof data['created_time'] === 'string' || data['created_time'] instanceof String)) {
            throw new Error("Expected the field `created_time` to be a primitive type in the JSON string but got " + data['created_time']);
        }
        // ensure the json data is a string
        if (data['news_content'] && !(typeof data['news_content'] === 'string' || data['news_content'] instanceof String)) {
            throw new Error("Expected the field `news_content` to be a primitive type in the JSON string but got " + data['news_content']);
        }
        // ensure the json data is a string
        if (data['news_sub_title'] && !(typeof data['news_sub_title'] === 'string' || data['news_sub_title'] instanceof String)) {
            throw new Error("Expected the field `news_sub_title` to be a primitive type in the JSON string but got " + data['news_sub_title']);
        }
        // ensure the json data is a string
        if (data['news_title'] && !(typeof data['news_title'] === 'string' || data['news_title'] instanceof String)) {
            throw new Error("Expected the field `news_title` to be a primitive type in the JSON string but got " + data['news_title']);
        }
        // ensure the json data is a string
        if (data['updated_time'] && !(typeof data['updated_time'] === 'string' || data['updated_time'] instanceof String)) {
            throw new Error("Expected the field `updated_time` to be a primitive type in the JSON string but got " + data['updated_time']);
        }

        return true;
    }


}



/**
 * @member {String} created_time
 */
NewsesResponseInner.prototype['created_time'] = undefined;

/**
 * @member {Number} id
 */
NewsesResponseInner.prototype['id'] = undefined;

/**
 * @member {String} news_content
 */
NewsesResponseInner.prototype['news_content'] = undefined;

/**
 * @member {String} news_sub_title
 */
NewsesResponseInner.prototype['news_sub_title'] = undefined;

/**
 * @member {String} news_title
 */
NewsesResponseInner.prototype['news_title'] = undefined;

/**
 * @member {String} updated_time
 */
NewsesResponseInner.prototype['updated_time'] = undefined;






export default NewsesResponseInner;

