/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewsInput model module.
 * @module model/NewsInput
 * @version 1.0.0
 */
class NewsInput {
    /**
     * Constructs a new <code>NewsInput</code>.
     * @alias module:model/NewsInput
     */
    constructor() { 
        
        NewsInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewsInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewsInput} obj Optional instance to populate.
     * @return {module:model/NewsInput} The populated <code>NewsInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewsInput();

            if (data.hasOwnProperty('news_content')) {
                obj['news_content'] = ApiClient.convertToType(data['news_content'], 'String');
            }
            if (data.hasOwnProperty('news_sub_title')) {
                obj['news_sub_title'] = ApiClient.convertToType(data['news_sub_title'], 'String');
            }
            if (data.hasOwnProperty('news_title')) {
                obj['news_title'] = ApiClient.convertToType(data['news_title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewsInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewsInput</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['news_content'] && !(typeof data['news_content'] === 'string' || data['news_content'] instanceof String)) {
            throw new Error("Expected the field `news_content` to be a primitive type in the JSON string but got " + data['news_content']);
        }
        // ensure the json data is a string
        if (data['news_sub_title'] && !(typeof data['news_sub_title'] === 'string' || data['news_sub_title'] instanceof String)) {
            throw new Error("Expected the field `news_sub_title` to be a primitive type in the JSON string but got " + data['news_sub_title']);
        }
        // ensure the json data is a string
        if (data['news_title'] && !(typeof data['news_title'] === 'string' || data['news_title'] instanceof String)) {
            throw new Error("Expected the field `news_title` to be a primitive type in the JSON string but got " + data['news_title']);
        }

        return true;
    }


}



/**
 * @member {String} news_content
 */
NewsInput.prototype['news_content'] = undefined;

/**
 * @member {String} news_sub_title
 */
NewsInput.prototype['news_sub_title'] = undefined;

/**
 * @member {String} news_title
 */
NewsInput.prototype['news_title'] = undefined;






export default NewsInput;

