/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaperPostRequest model module.
 * @module model/PaperPostRequest
 * @version 1.0.0
 */
class PaperPostRequest {
    /**
     * Constructs a new <code>PaperPostRequest</code>.
     * @alias module:model/PaperPostRequest
     */
    constructor() { 
        
        PaperPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaperPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaperPostRequest} obj Optional instance to populate.
     * @return {module:model/PaperPostRequest} The populated <code>PaperPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaperPostRequest();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('paper_authors')) {
                obj['paper_authors'] = ApiClient.convertToType(data['paper_authors'], ['String']);
            }
            if (data.hasOwnProperty('paper_link')) {
                obj['paper_link'] = ApiClient.convertToType(data['paper_link'], 'String');
            }
            if (data.hasOwnProperty('paper_origin')) {
                obj['paper_origin'] = ApiClient.convertToType(data['paper_origin'], 'String');
            }
            if (data.hasOwnProperty('paper_publish_year')) {
                obj['paper_publish_year'] = ApiClient.convertToType(data['paper_publish_year'], 'Number');
            }
            if (data.hasOwnProperty('paper_tags')) {
                obj['paper_tags'] = ApiClient.convertToType(data['paper_tags'], ['String']);
            }
            if (data.hasOwnProperty('paper_title')) {
                obj['paper_title'] = ApiClient.convertToType(data['paper_title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaperPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaperPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['paper_authors'])) {
            throw new Error("Expected the field `paper_authors` to be an array in the JSON data but got " + data['paper_authors']);
        }
        // ensure the json data is a string
        if (data['paper_link'] && !(typeof data['paper_link'] === 'string' || data['paper_link'] instanceof String)) {
            throw new Error("Expected the field `paper_link` to be a primitive type in the JSON string but got " + data['paper_link']);
        }
        // ensure the json data is a string
        if (data['paper_origin'] && !(typeof data['paper_origin'] === 'string' || data['paper_origin'] instanceof String)) {
            throw new Error("Expected the field `paper_origin` to be a primitive type in the JSON string but got " + data['paper_origin']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['paper_tags'])) {
            throw new Error("Expected the field `paper_tags` to be an array in the JSON data but got " + data['paper_tags']);
        }
        // ensure the json data is a string
        if (data['paper_title'] && !(typeof data['paper_title'] === 'string' || data['paper_title'] instanceof String)) {
            throw new Error("Expected the field `paper_title` to be a primitive type in the JSON string but got " + data['paper_title']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
PaperPostRequest.prototype['id'] = undefined;

/**
 * @member {Array.<String>} paper_authors
 */
PaperPostRequest.prototype['paper_authors'] = undefined;

/**
 * @member {String} paper_link
 */
PaperPostRequest.prototype['paper_link'] = undefined;

/**
 * @member {String} paper_origin
 */
PaperPostRequest.prototype['paper_origin'] = undefined;

/**
 * @member {Number} paper_publish_year
 */
PaperPostRequest.prototype['paper_publish_year'] = undefined;

/**
 * @member {Array.<String>} paper_tags
 */
PaperPostRequest.prototype['paper_tags'] = undefined;

/**
 * @member {String} paper_title
 */
PaperPostRequest.prototype['paper_title'] = undefined;






export default PaperPostRequest;

