/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectResponse model module.
 * @module model/ProjectResponse
 * @version 1.0.0
 */
class ProjectResponse {
    /**
     * Constructs a new <code>ProjectResponse</code>.
     * @alias module:model/ProjectResponse
     */
    constructor() { 
        
        ProjectResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectResponse} obj Optional instance to populate.
     * @return {module:model/ProjectResponse} The populated <code>ProjectResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectResponse();

            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project_description')) {
                obj['project_description'] = ApiClient.convertToType(data['project_description'], 'String');
            }
            if (data.hasOwnProperty('project_github')) {
                obj['project_github'] = ApiClient.convertToType(data['project_github'], 'String');
            }
            if (data.hasOwnProperty('project_link')) {
                obj['project_link'] = ApiClient.convertToType(data['project_link'], 'String');
            }
            if (data.hasOwnProperty('project_name')) {
                obj['project_name'] = ApiClient.convertToType(data['project_name'], 'String');
            }
            if (data.hasOwnProperty('project_tags')) {
                obj['project_tags'] = ApiClient.convertToType(data['project_tags'], ['String']);
            }
            if (data.hasOwnProperty('update_time')) {
                obj['update_time'] = ApiClient.convertToType(data['update_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['create_time'] && !(typeof data['create_time'] === 'string' || data['create_time'] instanceof String)) {
            throw new Error("Expected the field `create_time` to be a primitive type in the JSON string but got " + data['create_time']);
        }
        // ensure the json data is a string
        if (data['project_description'] && !(typeof data['project_description'] === 'string' || data['project_description'] instanceof String)) {
            throw new Error("Expected the field `project_description` to be a primitive type in the JSON string but got " + data['project_description']);
        }
        // ensure the json data is a string
        if (data['project_github'] && !(typeof data['project_github'] === 'string' || data['project_github'] instanceof String)) {
            throw new Error("Expected the field `project_github` to be a primitive type in the JSON string but got " + data['project_github']);
        }
        // ensure the json data is a string
        if (data['project_link'] && !(typeof data['project_link'] === 'string' || data['project_link'] instanceof String)) {
            throw new Error("Expected the field `project_link` to be a primitive type in the JSON string but got " + data['project_link']);
        }
        // ensure the json data is a string
        if (data['project_name'] && !(typeof data['project_name'] === 'string' || data['project_name'] instanceof String)) {
            throw new Error("Expected the field `project_name` to be a primitive type in the JSON string but got " + data['project_name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['project_tags'])) {
            throw new Error("Expected the field `project_tags` to be an array in the JSON data but got " + data['project_tags']);
        }
        // ensure the json data is a string
        if (data['update_time'] && !(typeof data['update_time'] === 'string' || data['update_time'] instanceof String)) {
            throw new Error("Expected the field `update_time` to be a primitive type in the JSON string but got " + data['update_time']);
        }

        return true;
    }


}



/**
 * @member {String} create_time
 */
ProjectResponse.prototype['create_time'] = undefined;

/**
 * @member {Number} id
 */
ProjectResponse.prototype['id'] = undefined;

/**
 * @member {String} project_description
 */
ProjectResponse.prototype['project_description'] = undefined;

/**
 * @member {String} project_github
 */
ProjectResponse.prototype['project_github'] = undefined;

/**
 * @member {String} project_link
 */
ProjectResponse.prototype['project_link'] = undefined;

/**
 * @member {String} project_name
 */
ProjectResponse.prototype['project_name'] = undefined;

/**
 * @member {Array.<String>} project_tags
 */
ProjectResponse.prototype['project_tags'] = undefined;

/**
 * @member {String} update_time
 */
ProjectResponse.prototype['update_time'] = undefined;






export default ProjectResponse;

