/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectTaskResponse model module.
 * @module model/ProjectTaskResponse
 * @version 1.0.0
 */
class ProjectTaskResponse {
    /**
     * Constructs a new <code>ProjectTaskResponse</code>.
     * @alias module:model/ProjectTaskResponse
     */
    constructor() { 
        
        ProjectTaskResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectTaskResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectTaskResponse} obj Optional instance to populate.
     * @return {module:model/ProjectTaskResponse} The populated <code>ProjectTaskResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectTaskResponse();

            if (data.hasOwnProperty('created_time')) {
                obj['created_time'] = ApiClient.convertToType(data['created_time'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('project_task_content')) {
                obj['project_task_content'] = ApiClient.convertToType(data['project_task_content'], 'String');
            }
            if (data.hasOwnProperty('project_task_sub_title')) {
                obj['project_task_sub_title'] = ApiClient.convertToType(data['project_task_sub_title'], 'String');
            }
            if (data.hasOwnProperty('project_task_title')) {
                obj['project_task_title'] = ApiClient.convertToType(data['project_task_title'], 'String');
            }
            if (data.hasOwnProperty('updated_time')) {
                obj['updated_time'] = ApiClient.convertToType(data['updated_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectTaskResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectTaskResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_time'] && !(typeof data['created_time'] === 'string' || data['created_time'] instanceof String)) {
            throw new Error("Expected the field `created_time` to be a primitive type in the JSON string but got " + data['created_time']);
        }
        // ensure the json data is a string
        if (data['project_task_content'] && !(typeof data['project_task_content'] === 'string' || data['project_task_content'] instanceof String)) {
            throw new Error("Expected the field `project_task_content` to be a primitive type in the JSON string but got " + data['project_task_content']);
        }
        // ensure the json data is a string
        if (data['project_task_sub_title'] && !(typeof data['project_task_sub_title'] === 'string' || data['project_task_sub_title'] instanceof String)) {
            throw new Error("Expected the field `project_task_sub_title` to be a primitive type in the JSON string but got " + data['project_task_sub_title']);
        }
        // ensure the json data is a string
        if (data['project_task_title'] && !(typeof data['project_task_title'] === 'string' || data['project_task_title'] instanceof String)) {
            throw new Error("Expected the field `project_task_title` to be a primitive type in the JSON string but got " + data['project_task_title']);
        }
        // ensure the json data is a string
        if (data['updated_time'] && !(typeof data['updated_time'] === 'string' || data['updated_time'] instanceof String)) {
            throw new Error("Expected the field `updated_time` to be a primitive type in the JSON string but got " + data['updated_time']);
        }

        return true;
    }


}



/**
 * @member {String} created_time
 */
ProjectTaskResponse.prototype['created_time'] = undefined;

/**
 * @member {Number} id
 */
ProjectTaskResponse.prototype['id'] = undefined;

/**
 * @member {Number} parent_id
 */
ProjectTaskResponse.prototype['parent_id'] = undefined;

/**
 * @member {Number} project_id
 */
ProjectTaskResponse.prototype['project_id'] = undefined;

/**
 * @member {String} project_task_content
 */
ProjectTaskResponse.prototype['project_task_content'] = undefined;

/**
 * @member {String} project_task_sub_title
 */
ProjectTaskResponse.prototype['project_task_sub_title'] = undefined;

/**
 * @member {String} project_task_title
 */
ProjectTaskResponse.prototype['project_task_title'] = undefined;

/**
 * @member {String} updated_time
 */
ProjectTaskResponse.prototype['updated_time'] = undefined;






export default ProjectTaskResponse;

