/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.ActivityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivityApi', function() {
    describe('activityActivityIdDelete', function() {
      it('should call activityActivityIdDelete successfully', function(done) {
        //uncomment below and update the code to test activityActivityIdDelete
        //instance.activityActivityIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('activityActivityIdGet', function() {
      it('should call activityActivityIdGet successfully', function(done) {
        //uncomment below and update the code to test activityActivityIdGet
        //instance.activityActivityIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('activityActivityIdPatch', function() {
      it('should call activityActivityIdPatch successfully', function(done) {
        //uncomment below and update the code to test activityActivityIdPatch
        //instance.activityActivityIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('activityActivityIdPut', function() {
      it('should call activityActivityIdPut successfully', function(done) {
        //uncomment below and update the code to test activityActivityIdPut
        //instance.activityActivityIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('activityGet', function() {
      it('should call activityGet successfully', function(done) {
        //uncomment below and update the code to test activityGet
        //instance.activityGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('activityPost', function() {
      it('should call activityPost successfully', function(done) {
        //uncomment below and update the code to test activityPost
        //instance.activityPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
