/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.MemberImageApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberImageApi', function() {
    describe('memberMemberIdMemberImageMemberImageUuidDelete', function() {
      it('should call memberMemberIdMemberImageMemberImageUuidDelete successfully', function(done) {
        //uncomment below and update the code to test memberMemberIdMemberImageMemberImageUuidDelete
        //instance.memberMemberIdMemberImageMemberImageUuidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberMemberIdMemberImageMemberImageUuidGet', function() {
      it('should call memberMemberIdMemberImageMemberImageUuidGet successfully', function(done) {
        //uncomment below and update the code to test memberMemberIdMemberImageMemberImageUuidGet
        //instance.memberMemberIdMemberImageMemberImageUuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberMemberIdMemberImagePost', function() {
      it('should call memberMemberIdMemberImagePost successfully', function(done) {
        //uncomment below and update the code to test memberMemberIdMemberImagePost
        //instance.memberMemberIdMemberImagePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
