/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MembersResponseInner model module.
 * @module model/MembersResponseInner
 * @version 1.0.0
 */
class MembersResponseInner {
    /**
     * Constructs a new <code>MembersResponseInner</code>.
     * @alias module:model/MembersResponseInner
     */
    constructor() { 
        
        MembersResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MembersResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MembersResponseInner} obj Optional instance to populate.
     * @return {module:model/MembersResponseInner} The populated <code>MembersResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MembersResponseInner();

            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'String');
            }
            if (data.hasOwnProperty('member_image')) {
                obj['member_image'] = ApiClient.convertToType(data['member_image'], 'String');
            }
            if (data.hasOwnProperty('member_intro')) {
                obj['member_intro'] = ApiClient.convertToType(data['member_intro'], 'String');
            }
            if (data.hasOwnProperty('member_name')) {
                obj['member_name'] = ApiClient.convertToType(data['member_name'], 'String');
            }
            if (data.hasOwnProperty('update_time')) {
                obj['update_time'] = ApiClient.convertToType(data['update_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MembersResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MembersResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['create_time'] && !(typeof data['create_time'] === 'string' || data['create_time'] instanceof String)) {
            throw new Error("Expected the field `create_time` to be a primitive type in the JSON string but got " + data['create_time']);
        }
        // ensure the json data is a string
        if (data['member_image'] && !(typeof data['member_image'] === 'string' || data['member_image'] instanceof String)) {
            throw new Error("Expected the field `member_image` to be a primitive type in the JSON string but got " + data['member_image']);
        }
        // ensure the json data is a string
        if (data['member_intro'] && !(typeof data['member_intro'] === 'string' || data['member_intro'] instanceof String)) {
            throw new Error("Expected the field `member_intro` to be a primitive type in the JSON string but got " + data['member_intro']);
        }
        // ensure the json data is a string
        if (data['member_name'] && !(typeof data['member_name'] === 'string' || data['member_name'] instanceof String)) {
            throw new Error("Expected the field `member_name` to be a primitive type in the JSON string but got " + data['member_name']);
        }
        // ensure the json data is a string
        if (data['update_time'] && !(typeof data['update_time'] === 'string' || data['update_time'] instanceof String)) {
            throw new Error("Expected the field `update_time` to be a primitive type in the JSON string but got " + data['update_time']);
        }

        return true;
    }


}



/**
 * @member {String} create_time
 */
MembersResponseInner.prototype['create_time'] = undefined;

/**
 * @member {String} member_image
 */
MembersResponseInner.prototype['member_image'] = undefined;

/**
 * @member {String} member_intro
 */
MembersResponseInner.prototype['member_intro'] = undefined;

/**
 * @member {String} member_name
 */
MembersResponseInner.prototype['member_name'] = undefined;

/**
 * @member {String} update_time
 */
MembersResponseInner.prototype['update_time'] = undefined;






export default MembersResponseInner;

