/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaperResponse model module.
 * @module model/PaperResponse
 * @version 1.0.0
 */
class PaperResponse {
    /**
     * Constructs a new <code>PaperResponse</code>.
     * @alias module:model/PaperResponse
     */
    constructor() { 
        
        PaperResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaperResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaperResponse} obj Optional instance to populate.
     * @return {module:model/PaperResponse} The populated <code>PaperResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaperResponse();

            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'String');
            }
            if (data.hasOwnProperty('paper_link')) {
                obj['paper_link'] = ApiClient.convertToType(data['paper_link'], 'String');
            }
            if (data.hasOwnProperty('paper_origin')) {
                obj['paper_origin'] = ApiClient.convertToType(data['paper_origin'], 'String');
            }
            if (data.hasOwnProperty('paper_publish_year')) {
                obj['paper_publish_year'] = ApiClient.convertToType(data['paper_publish_year'], 'Number');
            }
            if (data.hasOwnProperty('paper_title')) {
                obj['paper_title'] = ApiClient.convertToType(data['paper_title'], 'String');
            }
            if (data.hasOwnProperty('update_time')) {
                obj['update_time'] = ApiClient.convertToType(data['update_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaperResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaperResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['create_time'] && !(typeof data['create_time'] === 'string' || data['create_time'] instanceof String)) {
            throw new Error("Expected the field `create_time` to be a primitive type in the JSON string but got " + data['create_time']);
        }
        // ensure the json data is a string
        if (data['paper_link'] && !(typeof data['paper_link'] === 'string' || data['paper_link'] instanceof String)) {
            throw new Error("Expected the field `paper_link` to be a primitive type in the JSON string but got " + data['paper_link']);
        }
        // ensure the json data is a string
        if (data['paper_origin'] && !(typeof data['paper_origin'] === 'string' || data['paper_origin'] instanceof String)) {
            throw new Error("Expected the field `paper_origin` to be a primitive type in the JSON string but got " + data['paper_origin']);
        }
        // ensure the json data is a string
        if (data['paper_title'] && !(typeof data['paper_title'] === 'string' || data['paper_title'] instanceof String)) {
            throw new Error("Expected the field `paper_title` to be a primitive type in the JSON string but got " + data['paper_title']);
        }
        // ensure the json data is a string
        if (data['update_time'] && !(typeof data['update_time'] === 'string' || data['update_time'] instanceof String)) {
            throw new Error("Expected the field `update_time` to be a primitive type in the JSON string but got " + data['update_time']);
        }

        return true;
    }


}



/**
 * @member {String} create_time
 */
PaperResponse.prototype['create_time'] = undefined;

/**
 * @member {String} paper_link
 */
PaperResponse.prototype['paper_link'] = undefined;

/**
 * @member {String} paper_origin
 */
PaperResponse.prototype['paper_origin'] = undefined;

/**
 * @member {Number} paper_publish_year
 */
PaperResponse.prototype['paper_publish_year'] = undefined;

/**
 * @member {String} paper_title
 */
PaperResponse.prototype['paper_title'] = undefined;

/**
 * @member {String} update_time
 */
PaperResponse.prototype['update_time'] = undefined;






export default PaperResponse;

