/* tslint:disable */
/* eslint-disable */
/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    'description'?: string;
    /**
     * 
     * @type {ActivityResponse}
     * @memberof Activity
     */
    'response'?: ActivityResponse;
}
/**
 * 
 * @export
 * @interface ActivityImage
 */
export interface ActivityImage {
    /**
     * 
     * @type {string}
     * @memberof ActivityImage
     */
    'description'?: string;
    /**
     * 
     * @type {ActivityImageResponse}
     * @memberof ActivityImage
     */
    'response'?: ActivityImageResponse;
}
/**
 * 
 * @export
 * @interface ActivityImageResponse
 */
export interface ActivityImageResponse {
    /**
     * 
     * @type {number}
     * @memberof ActivityImageResponse
     */
    'activity_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityImageResponse
     */
    'create_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityImageResponse
     */
    'image_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityImageResponse
     */
    'image_uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityImageResponse
     */
    'update_time'?: string;
}
/**
 * 
 * @export
 * @interface ActivityPostRequest
 */
export interface ActivityPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ActivityPostRequest
     */
    'activity_sub_title': string;
    /**
     * 
     * @type {string}
     * @memberof ActivityPostRequest
     */
    'activity_title': string;
}
/**
 * 
 * @export
 * @interface ActivityResponse
 */
export interface ActivityResponse {
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    'activity_sub_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    'activity_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    'create_time'?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    'update_time'?: string;
}
/**
 * 
 * @export
 * @interface Member
 */
export interface Member {
    /**
     * 
     * @type {string}
     * @memberof Member
     */
    'description'?: string;
    /**
     * 
     * @type {MemberResponse}
     * @memberof Member
     */
    'response'?: MemberResponse;
}
/**
 * 
 * @export
 * @interface MemberInput
 */
export interface MemberInput {
    /**
     * 
     * @type {string}
     * @memberof MemberInput
     */
    'member_character'?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberInput
     */
    'member_intro'?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberInput
     */
    'member_name'?: string;
}
/**
 * 
 * @export
 * @interface MemberImage
 */
export interface MemberImage {
    /**
     * 
     * @type {string}
     * @memberof MemberImage
     */
    'description'?: string;
    /**
     * 
     * @type {MemberImageResponse}
     * @memberof MemberImage
     */
    'response'?: MemberImageResponse;
}
/**
 * 
 * @export
 * @interface MemberImageResponse
 */
export interface MemberImageResponse {
    /**
     * 
     * @type {string}
     * @memberof MemberImageResponse
     */
    'create_time'?: string;
    /**
     * 
     * @type {number}
     * @memberof MemberImageResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MemberImageResponse
     */
    'image_uuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof MemberImageResponse
     */
    'member_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MemberImageResponse
     */
    'update_time'?: string;
}
/**
 * 
 * @export
 * @interface MemberResponse
 */
export interface MemberResponse {
    /**
     * 
     * @type {string}
     * @memberof MemberResponse
     */
    'create_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResponse
     */
    'member_intro'?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResponse
     */
    'member_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResponse
     */
    'update_time'?: string;
}
/**
 * 
 * @export
 * @interface Members
 */
export interface Members {
    /**
     * 
     * @type {string}
     * @memberof Members
     */
    'description'?: string;
    /**
     * 
     * @type {Array<MembersResponseInner>}
     * @memberof Members
     */
    'response'?: Array<MembersResponseInner>;
}
/**
 * 
 * @export
 * @interface MembersResponseInner
 */
export interface MembersResponseInner {
    /**
     * 
     * @type {string}
     * @memberof MembersResponseInner
     */
    'create_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof MembersResponseInner
     */
    'member_image'?: string;
    /**
     * 
     * @type {string}
     * @memberof MembersResponseInner
     */
    'member_intro'?: string;
    /**
     * 
     * @type {string}
     * @memberof MembersResponseInner
     */
    'member_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof MembersResponseInner
     */
    'update_time'?: string;
}
/**
 * 
 * @export
 * @interface Paper
 */
export interface Paper {
    /**
     * 
     * @type {string}
     * @memberof Paper
     */
    'description'?: string;
    /**
     * 
     * @type {PaperResponse}
     * @memberof Paper
     */
    'response'?: PaperResponse;
}
/**
 * 
 * @export
 * @interface PaperAttachment
 */
export interface PaperAttachment {
    /**
     * 
     * @type {string}
     * @memberof PaperAttachment
     */
    'description'?: string;
    /**
     * 
     * @type {MemberImageResponse}
     * @memberof PaperAttachment
     */
    'response'?: MemberImageResponse;
}
/**
 * 
 * @export
 * @interface PaperPostRequest
 */
export interface PaperPostRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PaperPostRequest
     */
    'paper_authors'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PaperPostRequest
     */
    'paper_link'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperPostRequest
     */
    'paper_origin'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaperPostRequest
     */
    'paper_publish_year'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaperPostRequest
     */
    'paper_tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PaperPostRequest
     */
    'paper_title'?: string;
}
/**
 * 
 * @export
 * @interface PaperResponse
 */
export interface PaperResponse {
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    'create_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    'paper_link'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    'paper_origin'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaperResponse
     */
    'paper_publish_year'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    'paper_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    'update_time'?: string;
}

/**
 * ActivityApi - axios parameter creator
 * @export
 */
export const ActivityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary delete activity
         * @param {number} activityId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdDelete: async (activityId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityActivityIdDelete', 'activityId', activityId)
            const localVarPath = `/activity/{activity_id}`
                .replace(`{${"activity_id"}}`, encodeURIComponent(String(activityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary patch activity
         * @param {number} activityId 
         * @param {ActivityPostRequest} [activity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdPatch: async (activityId: number, activity?: ActivityPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityActivityIdPatch', 'activityId', activityId)
            const localVarPath = `/activity/{activity_id}`
                .replace(`{${"activity_id"}}`, encodeURIComponent(String(activityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(activity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get activity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary post activity
         * @param {ActivityPostRequest} [activity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityPost: async (activity?: ActivityPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(activity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ActivityApi - functional programming interface
 * @export
 */
export const ActivityApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ActivityApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary delete activity
         * @param {number} activityId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityActivityIdDelete(activityId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityActivityIdDelete(activityId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityApi.activityActivityIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary patch activity
         * @param {number} activityId 
         * @param {ActivityPostRequest} [activity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityActivityIdPatch(activityId: number, activity?: ActivityPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityActivityIdPatch(activityId, activity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityApi.activityActivityIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary get activity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityApi.activityGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary post activity
         * @param {ActivityPostRequest} [activity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityPost(activity?: ActivityPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Activity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityPost(activity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityApi.activityPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ActivityApi - factory interface
 * @export
 */
export const ActivityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ActivityApiFp(configuration)
    return {
        /**
         * 
         * @summary delete activity
         * @param {number} activityId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdDelete(activityId: number, options?: any): AxiosPromise<Activity> {
            return localVarFp.activityActivityIdDelete(activityId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary patch activity
         * @param {number} activityId 
         * @param {ActivityPostRequest} [activity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdPatch(activityId: number, activity?: ActivityPostRequest, options?: any): AxiosPromise<Activity> {
            return localVarFp.activityActivityIdPatch(activityId, activity, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get activity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityGet(options?: any): AxiosPromise<Activity> {
            return localVarFp.activityGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary post activity
         * @param {ActivityPostRequest} [activity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityPost(activity?: ActivityPostRequest, options?: any): AxiosPromise<Activity> {
            return localVarFp.activityPost(activity, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ActivityApi - object-oriented interface
 * @export
 * @class ActivityApi
 * @extends {BaseAPI}
 */
export class ActivityApi extends BaseAPI {
    /**
     * 
     * @summary delete activity
     * @param {number} activityId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityApi
     */
    public activityActivityIdDelete(activityId: number, options?: RawAxiosRequestConfig) {
        return ActivityApiFp(this.configuration).activityActivityIdDelete(activityId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary patch activity
     * @param {number} activityId 
     * @param {ActivityPostRequest} [activity] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityApi
     */
    public activityActivityIdPatch(activityId: number, activity?: ActivityPostRequest, options?: RawAxiosRequestConfig) {
        return ActivityApiFp(this.configuration).activityActivityIdPatch(activityId, activity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get activity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityApi
     */
    public activityGet(options?: RawAxiosRequestConfig) {
        return ActivityApiFp(this.configuration).activityGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary post activity
     * @param {ActivityPostRequest} [activity] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityApi
     */
    public activityPost(activity?: ActivityPostRequest, options?: RawAxiosRequestConfig) {
        return ActivityApiFp(this.configuration).activityPost(activity, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ActivityImageApi - axios parameter creator
 * @export
 */
export const ActivityImageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary delete activity image
         * @param {number} activityId 
         * @param {string} activityImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdActivityImageActivityImageUuidDelete: async (activityId: number, activityImageUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityActivityIdActivityImageActivityImageUuidDelete', 'activityId', activityId)
            // verify required parameter 'activityImageUuid' is not null or undefined
            assertParamExists('activityActivityIdActivityImageActivityImageUuidDelete', 'activityImageUuid', activityImageUuid)
            const localVarPath = `/activity/{activity_id}/activity-image/{activity_image_uuid}`
                .replace(`{${"activity_id"}}`, encodeURIComponent(String(activityId)))
                .replace(`{${"activity_image_uuid"}}`, encodeURIComponent(String(activityImageUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get activity image
         * @param {number} activityId 
         * @param {string} activityImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdActivityImageActivityImageUuidGet: async (activityId: number, activityImageUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityActivityIdActivityImageActivityImageUuidGet', 'activityId', activityId)
            // verify required parameter 'activityImageUuid' is not null or undefined
            assertParamExists('activityActivityIdActivityImageActivityImageUuidGet', 'activityImageUuid', activityImageUuid)
            const localVarPath = `/activity/{activity_id}/activity-image/{activity_image_uuid}`
                .replace(`{${"activity_id"}}`, encodeURIComponent(String(activityId)))
                .replace(`{${"activity_image_uuid"}}`, encodeURIComponent(String(activityImageUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary post activity image
         * @param {number} activityId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdActivityImagePost: async (activityId: number, image: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('activityActivityIdActivityImagePost', 'activityId', activityId)
            // verify required parameter 'image' is not null or undefined
            assertParamExists('activityActivityIdActivityImagePost', 'image', image)
            const localVarPath = `/activity/{activity_id}/activity-image`
                .replace(`{${"activity_id"}}`, encodeURIComponent(String(activityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ActivityImageApi - functional programming interface
 * @export
 */
export const ActivityImageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ActivityImageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary delete activity image
         * @param {number} activityId 
         * @param {string} activityImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityActivityIdActivityImageActivityImageUuidDelete(activityId: number, activityImageUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ActivityImage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityActivityIdActivityImageActivityImageUuidDelete(activityId, activityImageUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityImageApi.activityActivityIdActivityImageActivityImageUuidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary get activity image
         * @param {number} activityId 
         * @param {string} activityImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityActivityIdActivityImageActivityImageUuidGet(activityId: number, activityImageUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityActivityIdActivityImageActivityImageUuidGet(activityId, activityImageUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityImageApi.activityActivityIdActivityImageActivityImageUuidGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary post activity image
         * @param {number} activityId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activityActivityIdActivityImagePost(activityId: number, image: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ActivityImage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activityActivityIdActivityImagePost(activityId, image, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActivityImageApi.activityActivityIdActivityImagePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ActivityImageApi - factory interface
 * @export
 */
export const ActivityImageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ActivityImageApiFp(configuration)
    return {
        /**
         * 
         * @summary delete activity image
         * @param {number} activityId 
         * @param {string} activityImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdActivityImageActivityImageUuidDelete(activityId: number, activityImageUuid: string, options?: any): AxiosPromise<ActivityImage> {
            return localVarFp.activityActivityIdActivityImageActivityImageUuidDelete(activityId, activityImageUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get activity image
         * @param {number} activityId 
         * @param {string} activityImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdActivityImageActivityImageUuidGet(activityId: number, activityImageUuid: string, options?: any): AxiosPromise<void> {
            return localVarFp.activityActivityIdActivityImageActivityImageUuidGet(activityId, activityImageUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary post activity image
         * @param {number} activityId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activityActivityIdActivityImagePost(activityId: number, image: File, options?: any): AxiosPromise<ActivityImage> {
            return localVarFp.activityActivityIdActivityImagePost(activityId, image, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ActivityImageApi - object-oriented interface
 * @export
 * @class ActivityImageApi
 * @extends {BaseAPI}
 */
export class ActivityImageApi extends BaseAPI {
    /**
     * 
     * @summary delete activity image
     * @param {number} activityId 
     * @param {string} activityImageUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityImageApi
     */
    public activityActivityIdActivityImageActivityImageUuidDelete(activityId: number, activityImageUuid: string, options?: RawAxiosRequestConfig) {
        return ActivityImageApiFp(this.configuration).activityActivityIdActivityImageActivityImageUuidDelete(activityId, activityImageUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get activity image
     * @param {number} activityId 
     * @param {string} activityImageUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityImageApi
     */
    public activityActivityIdActivityImageActivityImageUuidGet(activityId: number, activityImageUuid: string, options?: RawAxiosRequestConfig) {
        return ActivityImageApiFp(this.configuration).activityActivityIdActivityImageActivityImageUuidGet(activityId, activityImageUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary post activity image
     * @param {number} activityId 
     * @param {File} image 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityImageApi
     */
    public activityActivityIdActivityImagePost(activityId: number, image: File, options?: RawAxiosRequestConfig) {
        return ActivityImageApiFp(this.configuration).activityActivityIdActivityImagePost(activityId, image, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MemberApi - axios parameter creator
 * @export
 */
export const MemberApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary get members
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/member`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary delete member
         * @param {number} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdDelete: async (memberId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('memberMemberIdDelete', 'memberId', memberId)
            const localVarPath = `/member/{member_id}`
                .replace(`{${"member_id"}}`, encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary patch member
         * @param {number} memberId 
         * @param {MemberInput} [member] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdPatch: async (memberId: number, member?: MemberInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('memberMemberIdPatch', 'memberId', memberId)
            const localVarPath = `/member/{member_id}`
                .replace(`{${"member_id"}}`, encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(member, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary post member
         * @param {MemberInput} [member] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberPost: async (member?: MemberInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/member`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(member, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemberApi - functional programming interface
 * @export
 */
export const MemberApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemberApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary get members
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Members>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberApi.memberGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary delete member
         * @param {number} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberMemberIdDelete(memberId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Member>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberMemberIdDelete(memberId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberApi.memberMemberIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary patch member
         * @param {number} memberId 
         * @param {MemberInput} [member] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberMemberIdPatch(memberId: number, member?: MemberInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Member>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberMemberIdPatch(memberId, member, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberApi.memberMemberIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary post member
         * @param {MemberInput} [member] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberPost(member?: MemberInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Member>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberPost(member, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberApi.memberPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MemberApi - factory interface
 * @export
 */
export const MemberApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemberApiFp(configuration)
    return {
        /**
         * 
         * @summary get members
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberGet(options?: any): AxiosPromise<Members> {
            return localVarFp.memberGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary delete member
         * @param {number} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdDelete(memberId: number, options?: any): AxiosPromise<Member> {
            return localVarFp.memberMemberIdDelete(memberId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary patch member
         * @param {number} memberId 
         * @param {MemberInput} [member] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdPatch(memberId: number, member?: MemberInput, options?: any): AxiosPromise<Member> {
            return localVarFp.memberMemberIdPatch(memberId, member, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary post member
         * @param {MemberInput} [member] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberPost(member?: MemberInput, options?: any): AxiosPromise<Member> {
            return localVarFp.memberPost(member, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemberApi - object-oriented interface
 * @export
 * @class MemberApi
 * @extends {BaseAPI}
 */
export class MemberApi extends BaseAPI {
    /**
     * 
     * @summary get members
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberApi
     */
    public memberGet(options?: RawAxiosRequestConfig) {
        return MemberApiFp(this.configuration).memberGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary delete member
     * @param {number} memberId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberApi
     */
    public memberMemberIdDelete(memberId: number, options?: RawAxiosRequestConfig) {
        return MemberApiFp(this.configuration).memberMemberIdDelete(memberId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary patch member
     * @param {number} memberId 
     * @param {MemberInput} [member] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberApi
     */
    public memberMemberIdPatch(memberId: number, member?: MemberInput, options?: RawAxiosRequestConfig) {
        return MemberApiFp(this.configuration).memberMemberIdPatch(memberId, member, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary post member
     * @param {MemberInput} [member] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberApi
     */
    public memberPost(member?: MemberInput, options?: RawAxiosRequestConfig) {
        return MemberApiFp(this.configuration).memberPost(member, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MemberImageApi - axios parameter creator
 * @export
 */
export const MemberImageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary delete member image
         * @param {number} memberId 
         * @param {string} memberImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdMemberImageMemberImageUuidDelete: async (memberId: number, memberImageUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('memberMemberIdMemberImageMemberImageUuidDelete', 'memberId', memberId)
            // verify required parameter 'memberImageUuid' is not null or undefined
            assertParamExists('memberMemberIdMemberImageMemberImageUuidDelete', 'memberImageUuid', memberImageUuid)
            const localVarPath = `/member/{member_id}/member-image/{member_image_uuid}`
                .replace(`{${"member_id"}}`, encodeURIComponent(String(memberId)))
                .replace(`{${"member_image_uuid"}}`, encodeURIComponent(String(memberImageUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get member images
         * @param {number} memberId 
         * @param {string} memberImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdMemberImageMemberImageUuidGet: async (memberId: number, memberImageUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('memberMemberIdMemberImageMemberImageUuidGet', 'memberId', memberId)
            // verify required parameter 'memberImageUuid' is not null or undefined
            assertParamExists('memberMemberIdMemberImageMemberImageUuidGet', 'memberImageUuid', memberImageUuid)
            const localVarPath = `/member/{member_id}/member-image/{member_image_uuid}`
                .replace(`{${"member_id"}}`, encodeURIComponent(String(memberId)))
                .replace(`{${"member_image_uuid"}}`, encodeURIComponent(String(memberImageUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary post member image
         * @param {number} memberId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdMemberImagePost: async (memberId: number, image: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('memberMemberIdMemberImagePost', 'memberId', memberId)
            // verify required parameter 'image' is not null or undefined
            assertParamExists('memberMemberIdMemberImagePost', 'image', image)
            const localVarPath = `/member/{member_id}/member-image`
                .replace(`{${"member_id"}}`, encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemberImageApi - functional programming interface
 * @export
 */
export const MemberImageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemberImageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary delete member image
         * @param {number} memberId 
         * @param {string} memberImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberMemberIdMemberImageMemberImageUuidDelete(memberId: number, memberImageUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaperAttachment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberMemberIdMemberImageMemberImageUuidDelete(memberId, memberImageUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberImageApi.memberMemberIdMemberImageMemberImageUuidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary get member images
         * @param {number} memberId 
         * @param {string} memberImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberMemberIdMemberImageMemberImageUuidGet(memberId: number, memberImageUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberMemberIdMemberImageMemberImageUuidGet(memberId, memberImageUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberImageApi.memberMemberIdMemberImageMemberImageUuidGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary post member image
         * @param {number} memberId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async memberMemberIdMemberImagePost(memberId: number, image: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MemberImage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.memberMemberIdMemberImagePost(memberId, image, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberImageApi.memberMemberIdMemberImagePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MemberImageApi - factory interface
 * @export
 */
export const MemberImageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemberImageApiFp(configuration)
    return {
        /**
         * 
         * @summary delete member image
         * @param {number} memberId 
         * @param {string} memberImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdMemberImageMemberImageUuidDelete(memberId: number, memberImageUuid: string, options?: any): AxiosPromise<PaperAttachment> {
            return localVarFp.memberMemberIdMemberImageMemberImageUuidDelete(memberId, memberImageUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get member images
         * @param {number} memberId 
         * @param {string} memberImageUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdMemberImageMemberImageUuidGet(memberId: number, memberImageUuid: string, options?: any): AxiosPromise<void> {
            return localVarFp.memberMemberIdMemberImageMemberImageUuidGet(memberId, memberImageUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary post member image
         * @param {number} memberId 
         * @param {File} image 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        memberMemberIdMemberImagePost(memberId: number, image: File, options?: any): AxiosPromise<MemberImage> {
            return localVarFp.memberMemberIdMemberImagePost(memberId, image, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemberImageApi - object-oriented interface
 * @export
 * @class MemberImageApi
 * @extends {BaseAPI}
 */
export class MemberImageApi extends BaseAPI {
    /**
     * 
     * @summary delete member image
     * @param {number} memberId 
     * @param {string} memberImageUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberImageApi
     */
    public memberMemberIdMemberImageMemberImageUuidDelete(memberId: number, memberImageUuid: string, options?: RawAxiosRequestConfig) {
        return MemberImageApiFp(this.configuration).memberMemberIdMemberImageMemberImageUuidDelete(memberId, memberImageUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get member images
     * @param {number} memberId 
     * @param {string} memberImageUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberImageApi
     */
    public memberMemberIdMemberImageMemberImageUuidGet(memberId: number, memberImageUuid: string, options?: RawAxiosRequestConfig) {
        return MemberImageApiFp(this.configuration).memberMemberIdMemberImageMemberImageUuidGet(memberId, memberImageUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary post member image
     * @param {number} memberId 
     * @param {File} image 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemberImageApi
     */
    public memberMemberIdMemberImagePost(memberId: number, image: File, options?: RawAxiosRequestConfig) {
        return MemberImageApiFp(this.configuration).memberMemberIdMemberImagePost(memberId, image, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PaperApi - axios parameter creator
 * @export
 */
export const PaperApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary get_papers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/paper`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary delete paper
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdDelete: async (paperId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('paperPaperIdDelete', 'paperId', paperId)
            const localVarPath = `/paper/{paper_id}`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary patch paper
         * @param {number} paperId 
         * @param {PaperPostRequest} [paper] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPatch: async (paperId: number, paper?: PaperPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('paperPaperIdPatch', 'paperId', paperId)
            const localVarPath = `/paper/{paper_id}`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paper, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary post paper
         * @param {PaperPostRequest} [paper] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPost: async (paper?: PaperPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/paper`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paper, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaperApi - functional programming interface
 * @export
 */
export const PaperApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaperApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary get_papers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Paper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperApi.paperGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary delete paper
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperPaperIdDelete(paperId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Paper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperPaperIdDelete(paperId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperApi.paperPaperIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary patch paper
         * @param {number} paperId 
         * @param {PaperPostRequest} [paper] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperPaperIdPatch(paperId: number, paper?: PaperPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Paper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperPaperIdPatch(paperId, paper, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperApi.paperPaperIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary post paper
         * @param {PaperPostRequest} [paper] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperPost(paper?: PaperPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Paper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperPost(paper, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperApi.paperPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaperApi - factory interface
 * @export
 */
export const PaperApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaperApiFp(configuration)
    return {
        /**
         * 
         * @summary get_papers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperGet(options?: any): AxiosPromise<Paper> {
            return localVarFp.paperGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary delete paper
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdDelete(paperId: number, options?: any): AxiosPromise<Paper> {
            return localVarFp.paperPaperIdDelete(paperId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary patch paper
         * @param {number} paperId 
         * @param {PaperPostRequest} [paper] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPatch(paperId: number, paper?: PaperPostRequest, options?: any): AxiosPromise<Paper> {
            return localVarFp.paperPaperIdPatch(paperId, paper, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary post paper
         * @param {PaperPostRequest} [paper] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPost(paper?: PaperPostRequest, options?: any): AxiosPromise<Paper> {
            return localVarFp.paperPost(paper, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaperApi - object-oriented interface
 * @export
 * @class PaperApi
 * @extends {BaseAPI}
 */
export class PaperApi extends BaseAPI {
    /**
     * 
     * @summary get_papers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperApi
     */
    public paperGet(options?: RawAxiosRequestConfig) {
        return PaperApiFp(this.configuration).paperGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary delete paper
     * @param {number} paperId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperApi
     */
    public paperPaperIdDelete(paperId: number, options?: RawAxiosRequestConfig) {
        return PaperApiFp(this.configuration).paperPaperIdDelete(paperId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary patch paper
     * @param {number} paperId 
     * @param {PaperPostRequest} [paper] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperApi
     */
    public paperPaperIdPatch(paperId: number, paper?: PaperPostRequest, options?: RawAxiosRequestConfig) {
        return PaperApiFp(this.configuration).paperPaperIdPatch(paperId, paper, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary post paper
     * @param {PaperPostRequest} [paper] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperApi
     */
    public paperPost(paper?: PaperPostRequest, options?: RawAxiosRequestConfig) {
        return PaperApiFp(this.configuration).paperPost(paper, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PaperAttachmentApi - axios parameter creator
 * @export
 */
export const PaperAttachmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary delete paper attachment
         * @param {number} paperId 
         * @param {string} paperAttachmentUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPaperAttachmentPaperAttachmentUuidDelete: async (paperId: number, paperAttachmentUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('paperPaperIdPaperAttachmentPaperAttachmentUuidDelete', 'paperId', paperId)
            // verify required parameter 'paperAttachmentUuid' is not null or undefined
            assertParamExists('paperPaperIdPaperAttachmentPaperAttachmentUuidDelete', 'paperAttachmentUuid', paperAttachmentUuid)
            const localVarPath = `/paper/{paper_id}/paper-attachment/{paper_attachment_uuid}`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)))
                .replace(`{${"paper_attachment_uuid"}}`, encodeURIComponent(String(paperAttachmentUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get paper attachment
         * @param {number} paperId 
         * @param {string} paperAttachmentUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPaperAttachmentPaperAttachmentUuidGet: async (paperId: number, paperAttachmentUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('paperPaperIdPaperAttachmentPaperAttachmentUuidGet', 'paperId', paperId)
            // verify required parameter 'paperAttachmentUuid' is not null or undefined
            assertParamExists('paperPaperIdPaperAttachmentPaperAttachmentUuidGet', 'paperAttachmentUuid', paperAttachmentUuid)
            const localVarPath = `/paper/{paper_id}/paper-attachment/{paper_attachment_uuid}`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)))
                .replace(`{${"paper_attachment_uuid"}}`, encodeURIComponent(String(paperAttachmentUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary post paper attachment
         * @param {number} paperId 
         * @param {File} paperAttachment 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPaperAttachmentPost: async (paperId: number, paperAttachment: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('paperPaperIdPaperAttachmentPost', 'paperId', paperId)
            // verify required parameter 'paperAttachment' is not null or undefined
            assertParamExists('paperPaperIdPaperAttachmentPost', 'paperAttachment', paperAttachment)
            const localVarPath = `/paper/{paper_id}/paper-attachment`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (paperAttachment !== undefined) { 
                localVarFormParams.append('paper_attachment', paperAttachment as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaperAttachmentApi - functional programming interface
 * @export
 */
export const PaperAttachmentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaperAttachmentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary delete paper attachment
         * @param {number} paperId 
         * @param {string} paperAttachmentUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId: number, paperAttachmentUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaperAttachment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId, paperAttachmentUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperAttachmentApi.paperPaperIdPaperAttachmentPaperAttachmentUuidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary get paper attachment
         * @param {number} paperId 
         * @param {string} paperAttachmentUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId: number, paperAttachmentUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId, paperAttachmentUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperAttachmentApi.paperPaperIdPaperAttachmentPaperAttachmentUuidGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary post paper attachment
         * @param {number} paperId 
         * @param {File} paperAttachment 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paperPaperIdPaperAttachmentPost(paperId: number, paperAttachment: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaperAttachment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paperPaperIdPaperAttachmentPost(paperId, paperAttachment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperAttachmentApi.paperPaperIdPaperAttachmentPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaperAttachmentApi - factory interface
 * @export
 */
export const PaperAttachmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaperAttachmentApiFp(configuration)
    return {
        /**
         * 
         * @summary delete paper attachment
         * @param {number} paperId 
         * @param {string} paperAttachmentUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId: number, paperAttachmentUuid: string, options?: any): AxiosPromise<PaperAttachment> {
            return localVarFp.paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId, paperAttachmentUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get paper attachment
         * @param {number} paperId 
         * @param {string} paperAttachmentUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId: number, paperAttachmentUuid: string, options?: any): AxiosPromise<void> {
            return localVarFp.paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId, paperAttachmentUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary post paper attachment
         * @param {number} paperId 
         * @param {File} paperAttachment 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paperPaperIdPaperAttachmentPost(paperId: number, paperAttachment: File, options?: any): AxiosPromise<PaperAttachment> {
            return localVarFp.paperPaperIdPaperAttachmentPost(paperId, paperAttachment, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaperAttachmentApi - object-oriented interface
 * @export
 * @class PaperAttachmentApi
 * @extends {BaseAPI}
 */
export class PaperAttachmentApi extends BaseAPI {
    /**
     * 
     * @summary delete paper attachment
     * @param {number} paperId 
     * @param {string} paperAttachmentUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperAttachmentApi
     */
    public paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId: number, paperAttachmentUuid: string, options?: RawAxiosRequestConfig) {
        return PaperAttachmentApiFp(this.configuration).paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId, paperAttachmentUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get paper attachment
     * @param {number} paperId 
     * @param {string} paperAttachmentUuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperAttachmentApi
     */
    public paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId: number, paperAttachmentUuid: string, options?: RawAxiosRequestConfig) {
        return PaperAttachmentApiFp(this.configuration).paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId, paperAttachmentUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary post paper attachment
     * @param {number} paperId 
     * @param {File} paperAttachment 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaperAttachmentApi
     */
    public paperPaperIdPaperAttachmentPost(paperId: number, paperAttachment: File, options?: RawAxiosRequestConfig) {
        return PaperAttachmentApiFp(this.configuration).paperPaperIdPaperAttachmentPost(paperId, paperAttachment, options).then((request) => request(this.axios, this.basePath));
    }
}



