/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Activity from './model/Activity';
import ActivityImage from './model/ActivityImage';
import ActivityImageResponse from './model/ActivityImageResponse';
import ActivityResponse from './model/ActivityResponse';
import Member from './model/Member';
import MemberImage from './model/MemberImage';
import MemberImageResponse from './model/MemberImageResponse';
import MemberResponse from './model/MemberResponse';
import Members from './model/Members';
import MembersResponseInner from './model/MembersResponseInner';
import Paper from './model/Paper';
import PaperAttachment from './model/PaperAttachment';
import PaperAuthor from './model/PaperAuthor';
import PaperAuthorResponse from './model/PaperAuthorResponse';
import PaperAuthors from './model/PaperAuthors';
import PaperResponse from './model/PaperResponse';
import PaperTag from './model/PaperTag';
import PaperTagResponse from './model/PaperTagResponse';
import PaperTags from './model/PaperTags';
import Papers from './model/Papers';
import PapersResponseInner from './model/PapersResponseInner';
import ActivityApi from './api/ActivityApi';
import ActivityImageApi from './api/ActivityImageApi';
import MemberApi from './api/MemberApi';
import MemberImageApi from './api/MemberImageApi';
import PaperApi from './api/PaperApi';
import PaperAttachmentApi from './api/PaperAttachmentApi';
import PaperAuthorApi from './api/PaperAuthorApi';
import PaperTagApi from './api/PaperTagApi';


/**
* Nation Central University WIDM LAB back-end API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WidmBackEnd = require('index'); // See note below*.
* var xxxSvc = new WidmBackEnd.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WidmBackEnd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WidmBackEnd.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WidmBackEnd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Activity model constructor.
     * @property {module:model/Activity}
     */
    Activity,

    /**
     * The ActivityImage model constructor.
     * @property {module:model/ActivityImage}
     */
    ActivityImage,

    /**
     * The ActivityImageResponse model constructor.
     * @property {module:model/ActivityImageResponse}
     */
    ActivityImageResponse,

    /**
     * The ActivityResponse model constructor.
     * @property {module:model/ActivityResponse}
     */
    ActivityResponse,

    /**
     * The Member model constructor.
     * @property {module:model/Member}
     */
    Member,

    /**
     * The MemberImage model constructor.
     * @property {module:model/MemberImage}
     */
    MemberImage,

    /**
     * The MemberImageResponse model constructor.
     * @property {module:model/MemberImageResponse}
     */
    MemberImageResponse,

    /**
     * The MemberResponse model constructor.
     * @property {module:model/MemberResponse}
     */
    MemberResponse,

    /**
     * The Members model constructor.
     * @property {module:model/Members}
     */
    Members,

    /**
     * The MembersResponseInner model constructor.
     * @property {module:model/MembersResponseInner}
     */
    MembersResponseInner,

    /**
     * The Paper model constructor.
     * @property {module:model/Paper}
     */
    Paper,

    /**
     * The PaperAttachment model constructor.
     * @property {module:model/PaperAttachment}
     */
    PaperAttachment,

    /**
     * The PaperAuthor model constructor.
     * @property {module:model/PaperAuthor}
     */
    PaperAuthor,

    /**
     * The PaperAuthorResponse model constructor.
     * @property {module:model/PaperAuthorResponse}
     */
    PaperAuthorResponse,

    /**
     * The PaperAuthors model constructor.
     * @property {module:model/PaperAuthors}
     */
    PaperAuthors,

    /**
     * The PaperResponse model constructor.
     * @property {module:model/PaperResponse}
     */
    PaperResponse,

    /**
     * The PaperTag model constructor.
     * @property {module:model/PaperTag}
     */
    PaperTag,

    /**
     * The PaperTagResponse model constructor.
     * @property {module:model/PaperTagResponse}
     */
    PaperTagResponse,

    /**
     * The PaperTags model constructor.
     * @property {module:model/PaperTags}
     */
    PaperTags,

    /**
     * The Papers model constructor.
     * @property {module:model/Papers}
     */
    Papers,

    /**
     * The PapersResponseInner model constructor.
     * @property {module:model/PapersResponseInner}
     */
    PapersResponseInner,

    /**
    * The ActivityApi service constructor.
    * @property {module:api/ActivityApi}
    */
    ActivityApi,

    /**
    * The ActivityImageApi service constructor.
    * @property {module:api/ActivityImageApi}
    */
    ActivityImageApi,

    /**
    * The MemberApi service constructor.
    * @property {module:api/MemberApi}
    */
    MemberApi,

    /**
    * The MemberImageApi service constructor.
    * @property {module:api/MemberImageApi}
    */
    MemberImageApi,

    /**
    * The PaperApi service constructor.
    * @property {module:api/PaperApi}
    */
    PaperApi,

    /**
    * The PaperAttachmentApi service constructor.
    * @property {module:api/PaperAttachmentApi}
    */
    PaperAttachmentApi,

    /**
    * The PaperAuthorApi service constructor.
    * @property {module:api/PaperAuthorApi}
    */
    PaperAuthorApi,

    /**
    * The PaperTagApi service constructor.
    * @property {module:api/PaperTagApi}
    */
    PaperTagApi
};
