/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Activities from './model/Activities';
import ActivitiesResponseInner from './model/ActivitiesResponseInner';
import Activity from './model/Activity';
import ActivityImage from './model/ActivityImage';
import ActivityImageResponse from './model/ActivityImageResponse';
import ActivityPostRequest from './model/ActivityPostRequest';
import ActivityResponse from './model/ActivityResponse';
import Member from './model/Member';
import MemberImage from './model/MemberImage';
import MemberImageResponse from './model/MemberImageResponse';
import MemberInput from './model/MemberInput';
import MemberResponse from './model/MemberResponse';
import Members from './model/Members';
import MembersResponseInner from './model/MembersResponseInner';
import News from './model/News';
import NewsImage from './model/NewsImage';
import NewsImageResponse from './model/NewsImageResponse';
import NewsImages from './model/NewsImages';
import NewsInput from './model/NewsInput';
import Newses from './model/Newses';
import NewsesResponseInner from './model/NewsesResponseInner';
import Paper from './model/Paper';
import PaperAttachment from './model/PaperAttachment';
import PaperPaperIdPatchRequest from './model/PaperPaperIdPatchRequest';
import PaperPostRequest from './model/PaperPostRequest';
import PaperResponse from './model/PaperResponse';
import Papers from './model/Papers';
import PapersResponseInner from './model/PapersResponseInner';
import Project from './model/Project';
import ProjectIcon from './model/ProjectIcon';
import ProjectIconResponse from './model/ProjectIconResponse';
import ProjectInput from './model/ProjectInput';
import ProjectResponse from './model/ProjectResponse';
import ProjectTask from './model/ProjectTask';
import ProjectTaskImage from './model/ProjectTaskImage';
import ProjectTaskImages from './model/ProjectTaskImages';
import ProjectTaskInput from './model/ProjectTaskInput';
import ProjectTaskResponse from './model/ProjectTaskResponse';
import ProjectTasks from './model/ProjectTasks';
import ProjectTasksResponseInner from './model/ProjectTasksResponseInner';
import ProjectTasksResponseInnerChildrenInner from './model/ProjectTasksResponseInnerChildrenInner';
import Projects from './model/Projects';
import ProjectsResponseInner from './model/ProjectsResponseInner';
import ActivityApi from './api/ActivityApi';
import ActivityImageApi from './api/ActivityImageApi';
import MemberApi from './api/MemberApi';
import MemberImageApi from './api/MemberImageApi';
import NewsApi from './api/NewsApi';
import NewsImageApi from './api/NewsImageApi';
import PaperApi from './api/PaperApi';
import PaperAttachmentApi from './api/PaperAttachmentApi';
import ProjectApi from './api/ProjectApi';
import ProjectIconApi from './api/ProjectIconApi';
import ProjectTaskApi from './api/ProjectTaskApi';
import ProjectTaskImageApi from './api/ProjectTaskImageApi';


/**
* Nation Central University WIDM LAB back-end API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WidmBackEnd = require('index'); // See note below*.
* var xxxSvc = new WidmBackEnd.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WidmBackEnd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WidmBackEnd.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WidmBackEnd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Activities model constructor.
     * @property {module:model/Activities}
     */
    Activities,

    /**
     * The ActivitiesResponseInner model constructor.
     * @property {module:model/ActivitiesResponseInner}
     */
    ActivitiesResponseInner,

    /**
     * The Activity model constructor.
     * @property {module:model/Activity}
     */
    Activity,

    /**
     * The ActivityImage model constructor.
     * @property {module:model/ActivityImage}
     */
    ActivityImage,

    /**
     * The ActivityImageResponse model constructor.
     * @property {module:model/ActivityImageResponse}
     */
    ActivityImageResponse,

    /**
     * The ActivityPostRequest model constructor.
     * @property {module:model/ActivityPostRequest}
     */
    ActivityPostRequest,

    /**
     * The ActivityResponse model constructor.
     * @property {module:model/ActivityResponse}
     */
    ActivityResponse,

    /**
     * The Member model constructor.
     * @property {module:model/Member}
     */
    Member,

    /**
     * The MemberImage model constructor.
     * @property {module:model/MemberImage}
     */
    MemberImage,

    /**
     * The MemberImageResponse model constructor.
     * @property {module:model/MemberImageResponse}
     */
    MemberImageResponse,

    /**
     * The MemberInput model constructor.
     * @property {module:model/MemberInput}
     */
    MemberInput,

    /**
     * The MemberResponse model constructor.
     * @property {module:model/MemberResponse}
     */
    MemberResponse,

    /**
     * The Members model constructor.
     * @property {module:model/Members}
     */
    Members,

    /**
     * The MembersResponseInner model constructor.
     * @property {module:model/MembersResponseInner}
     */
    MembersResponseInner,

    /**
     * The News model constructor.
     * @property {module:model/News}
     */
    News,

    /**
     * The NewsImage model constructor.
     * @property {module:model/NewsImage}
     */
    NewsImage,

    /**
     * The NewsImageResponse model constructor.
     * @property {module:model/NewsImageResponse}
     */
    NewsImageResponse,

    /**
     * The NewsImages model constructor.
     * @property {module:model/NewsImages}
     */
    NewsImages,

    /**
     * The NewsInput model constructor.
     * @property {module:model/NewsInput}
     */
    NewsInput,

    /**
     * The Newses model constructor.
     * @property {module:model/Newses}
     */
    Newses,

    /**
     * The NewsesResponseInner model constructor.
     * @property {module:model/NewsesResponseInner}
     */
    NewsesResponseInner,

    /**
     * The Paper model constructor.
     * @property {module:model/Paper}
     */
    Paper,

    /**
     * The PaperAttachment model constructor.
     * @property {module:model/PaperAttachment}
     */
    PaperAttachment,

    /**
     * The PaperPaperIdPatchRequest model constructor.
     * @property {module:model/PaperPaperIdPatchRequest}
     */
    PaperPaperIdPatchRequest,

    /**
     * The PaperPostRequest model constructor.
     * @property {module:model/PaperPostRequest}
     */
    PaperPostRequest,

    /**
     * The PaperResponse model constructor.
     * @property {module:model/PaperResponse}
     */
    PaperResponse,

    /**
     * The Papers model constructor.
     * @property {module:model/Papers}
     */
    Papers,

    /**
     * The PapersResponseInner model constructor.
     * @property {module:model/PapersResponseInner}
     */
    PapersResponseInner,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The ProjectIcon model constructor.
     * @property {module:model/ProjectIcon}
     */
    ProjectIcon,

    /**
     * The ProjectIconResponse model constructor.
     * @property {module:model/ProjectIconResponse}
     */
    ProjectIconResponse,

    /**
     * The ProjectInput model constructor.
     * @property {module:model/ProjectInput}
     */
    ProjectInput,

    /**
     * The ProjectResponse model constructor.
     * @property {module:model/ProjectResponse}
     */
    ProjectResponse,

    /**
     * The ProjectTask model constructor.
     * @property {module:model/ProjectTask}
     */
    ProjectTask,

    /**
     * The ProjectTaskImage model constructor.
     * @property {module:model/ProjectTaskImage}
     */
    ProjectTaskImage,

    /**
     * The ProjectTaskImages model constructor.
     * @property {module:model/ProjectTaskImages}
     */
    ProjectTaskImages,

    /**
     * The ProjectTaskInput model constructor.
     * @property {module:model/ProjectTaskInput}
     */
    ProjectTaskInput,

    /**
     * The ProjectTaskResponse model constructor.
     * @property {module:model/ProjectTaskResponse}
     */
    ProjectTaskResponse,

    /**
     * The ProjectTasks model constructor.
     * @property {module:model/ProjectTasks}
     */
    ProjectTasks,

    /**
     * The ProjectTasksResponseInner model constructor.
     * @property {module:model/ProjectTasksResponseInner}
     */
    ProjectTasksResponseInner,

    /**
     * The ProjectTasksResponseInnerChildrenInner model constructor.
     * @property {module:model/ProjectTasksResponseInnerChildrenInner}
     */
    ProjectTasksResponseInnerChildrenInner,

    /**
     * The Projects model constructor.
     * @property {module:model/Projects}
     */
    Projects,

    /**
     * The ProjectsResponseInner model constructor.
     * @property {module:model/ProjectsResponseInner}
     */
    ProjectsResponseInner,

    /**
    * The ActivityApi service constructor.
    * @property {module:api/ActivityApi}
    */
    ActivityApi,

    /**
    * The ActivityImageApi service constructor.
    * @property {module:api/ActivityImageApi}
    */
    ActivityImageApi,

    /**
    * The MemberApi service constructor.
    * @property {module:api/MemberApi}
    */
    MemberApi,

    /**
    * The MemberImageApi service constructor.
    * @property {module:api/MemberImageApi}
    */
    MemberImageApi,

    /**
    * The NewsApi service constructor.
    * @property {module:api/NewsApi}
    */
    NewsApi,

    /**
    * The NewsImageApi service constructor.
    * @property {module:api/NewsImageApi}
    */
    NewsImageApi,

    /**
    * The PaperApi service constructor.
    * @property {module:api/PaperApi}
    */
    PaperApi,

    /**
    * The PaperAttachmentApi service constructor.
    * @property {module:api/PaperAttachmentApi}
    */
    PaperAttachmentApi,

    /**
    * The ProjectApi service constructor.
    * @property {module:api/ProjectApi}
    */
    ProjectApi,

    /**
    * The ProjectIconApi service constructor.
    * @property {module:api/ProjectIconApi}
    */
    ProjectIconApi,

    /**
    * The ProjectTaskApi service constructor.
    * @property {module:api/ProjectTaskApi}
    */
    ProjectTaskApi,

    /**
    * The ProjectTaskImageApi service constructor.
    * @property {module:api/ProjectTaskImageApi}
    */
    ProjectTaskImageApi
};
