/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Paper from '../model/Paper';
import Papers from '../model/Papers';

/**
* Paper service.
* @module api/PaperApi
* @version 1.0.0
*/
export default class PaperApi {

    /**
    * Constructs a new PaperApi. 
    * @alias module:api/PaperApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * get_papers
     * @param {Object} opts Optional parameters
     * @param {String} [paperTag] 
     * @param {String} [paperAuthor] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Papers} and HTTP response
     */
    paperGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'paper_tag': opts['paperTag'],
        'paper_author': opts['paperAuthor']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Papers;
      return this.apiClient.callApi(
        '/paper', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * get_papers
     * @param {Object} opts Optional parameters
     * @param {String} opts.paperTag 
     * @param {String} opts.paperAuthor 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Papers}
     */
    paperGet(opts) {
      return this.paperGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * delete paper
     * @param {Number} paperId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Paper} and HTTP response
     */
    paperPaperIdDeleteWithHttpInfo(paperId) {
      let postBody = null;
      // verify the required parameter 'paperId' is set
      if (paperId === undefined || paperId === null) {
        throw new Error("Missing the required parameter 'paperId' when calling paperPaperIdDelete");
      }

      let pathParams = {
        'paper_id': paperId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Paper;
      return this.apiClient.callApi(
        '/paper/{paper_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * delete paper
     * @param {Number} paperId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Paper}
     */
    paperPaperIdDelete(paperId) {
      return this.paperPaperIdDeleteWithHttpInfo(paperId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * patch paper
     * @param {Number} paperId 
     * @param {Object} opts Optional parameters
     * @param {Number} [paperPublishYear] 
     * @param {String} [paperTitle] 
     * @param {String} [paperOrigin] 
     * @param {String} [paperLink] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Paper} and HTTP response
     */
    paperPaperIdPatchWithHttpInfo(paperId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'paperId' is set
      if (paperId === undefined || paperId === null) {
        throw new Error("Missing the required parameter 'paperId' when calling paperPaperIdPatch");
      }

      let pathParams = {
        'paper_id': paperId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'paper_publish_year': opts['paperPublishYear'],
        'paper_title': opts['paperTitle'],
        'paper_origin': opts['paperOrigin'],
        'paper_link': opts['paperLink']
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Paper;
      return this.apiClient.callApi(
        '/paper/{paper_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * patch paper
     * @param {Number} paperId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.paperPublishYear 
     * @param {String} opts.paperTitle 
     * @param {String} opts.paperOrigin 
     * @param {String} opts.paperLink 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Paper}
     */
    paperPaperIdPatch(paperId, opts) {
      return this.paperPaperIdPatchWithHttpInfo(paperId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * put paper
     * @param {Number} paperId 
     * @param {Number} paperPublishYear 
     * @param {String} paperTitle 
     * @param {String} paperOrigin 
     * @param {String} paperLink 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Paper} and HTTP response
     */
    paperPaperIdPutWithHttpInfo(paperId, paperPublishYear, paperTitle, paperOrigin, paperLink) {
      let postBody = null;
      // verify the required parameter 'paperId' is set
      if (paperId === undefined || paperId === null) {
        throw new Error("Missing the required parameter 'paperId' when calling paperPaperIdPut");
      }
      // verify the required parameter 'paperPublishYear' is set
      if (paperPublishYear === undefined || paperPublishYear === null) {
        throw new Error("Missing the required parameter 'paperPublishYear' when calling paperPaperIdPut");
      }
      // verify the required parameter 'paperTitle' is set
      if (paperTitle === undefined || paperTitle === null) {
        throw new Error("Missing the required parameter 'paperTitle' when calling paperPaperIdPut");
      }
      // verify the required parameter 'paperOrigin' is set
      if (paperOrigin === undefined || paperOrigin === null) {
        throw new Error("Missing the required parameter 'paperOrigin' when calling paperPaperIdPut");
      }
      // verify the required parameter 'paperLink' is set
      if (paperLink === undefined || paperLink === null) {
        throw new Error("Missing the required parameter 'paperLink' when calling paperPaperIdPut");
      }

      let pathParams = {
        'paper_id': paperId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'paper_publish_year': paperPublishYear,
        'paper_title': paperTitle,
        'paper_origin': paperOrigin,
        'paper_link': paperLink
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Paper;
      return this.apiClient.callApi(
        '/paper/{paper_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * put paper
     * @param {Number} paperId 
     * @param {Number} paperPublishYear 
     * @param {String} paperTitle 
     * @param {String} paperOrigin 
     * @param {String} paperLink 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Paper}
     */
    paperPaperIdPut(paperId, paperPublishYear, paperTitle, paperOrigin, paperLink) {
      return this.paperPaperIdPutWithHttpInfo(paperId, paperPublishYear, paperTitle, paperOrigin, paperLink)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * post paper
     * @param {Number} paperPublishYear 
     * @param {String} paperTitle 
     * @param {String} paperOrigin 
     * @param {String} paperLink 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Paper} and HTTP response
     */
    paperPostWithHttpInfo(paperPublishYear, paperTitle, paperOrigin, paperLink) {
      let postBody = null;
      // verify the required parameter 'paperPublishYear' is set
      if (paperPublishYear === undefined || paperPublishYear === null) {
        throw new Error("Missing the required parameter 'paperPublishYear' when calling paperPost");
      }
      // verify the required parameter 'paperTitle' is set
      if (paperTitle === undefined || paperTitle === null) {
        throw new Error("Missing the required parameter 'paperTitle' when calling paperPost");
      }
      // verify the required parameter 'paperOrigin' is set
      if (paperOrigin === undefined || paperOrigin === null) {
        throw new Error("Missing the required parameter 'paperOrigin' when calling paperPost");
      }
      // verify the required parameter 'paperLink' is set
      if (paperLink === undefined || paperLink === null) {
        throw new Error("Missing the required parameter 'paperLink' when calling paperPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'paper_publish_year': paperPublishYear,
        'paper_title': paperTitle,
        'paper_origin': paperOrigin,
        'paper_link': paperLink
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Paper;
      return this.apiClient.callApi(
        '/paper', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * post paper
     * @param {Number} paperPublishYear 
     * @param {String} paperTitle 
     * @param {String} paperOrigin 
     * @param {String} paperLink 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Paper}
     */
    paperPost(paperPublishYear, paperTitle, paperOrigin, paperLink) {
      return this.paperPostWithHttpInfo(paperPublishYear, paperTitle, paperOrigin, paperLink)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
