/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Activity from '../model/Activity';

/**
* Activity service.
* @module api/ActivityApi
* @version 1.0.0
*/
export default class ActivityApi {

    /**
    * Constructs a new ActivityApi. 
    * @alias module:api/ActivityApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the activityActivityIdDelete operation.
     * @callback module:api/ActivityApi~activityActivityIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Activity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete activity
     * @param {Number} activityId 
     * @param {module:api/ActivityApi~activityActivityIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Activity}
     */
    activityActivityIdDelete(activityId, callback) {
      let postBody = null;
      // verify the required parameter 'activityId' is set
      if (activityId === undefined || activityId === null) {
        throw new Error("Missing the required parameter 'activityId' when calling activityActivityIdDelete");
      }

      let pathParams = {
        'activity_id': activityId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Activity;
      return this.apiClient.callApi(
        '/activity/{activity_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the activityActivityIdGet operation.
     * @callback module:api/ActivityApi~activityActivityIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Activity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get activity
     * @param {Number} activityId 
     * @param {module:api/ActivityApi~activityActivityIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Activity}
     */
    activityActivityIdGet(activityId, callback) {
      let postBody = null;
      // verify the required parameter 'activityId' is set
      if (activityId === undefined || activityId === null) {
        throw new Error("Missing the required parameter 'activityId' when calling activityActivityIdGet");
      }

      let pathParams = {
        'activity_id': activityId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Activity;
      return this.apiClient.callApi(
        '/activity/{activity_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the activityActivityIdPatch operation.
     * @callback module:api/ActivityApi~activityActivityIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Activity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * patch activity
     * @param {Number} activityId 
     * @param {Object} opts Optional parameters
     * @param {String} [activityTitle] 
     * @param {String} [activitySubTitle] 
     * @param {module:api/ActivityApi~activityActivityIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Activity}
     */
    activityActivityIdPatch(activityId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'activityId' is set
      if (activityId === undefined || activityId === null) {
        throw new Error("Missing the required parameter 'activityId' when calling activityActivityIdPatch");
      }

      let pathParams = {
        'activity_id': activityId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'activity_title': opts['activityTitle'],
        'activity_sub_title': opts['activitySubTitle']
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Activity;
      return this.apiClient.callApi(
        '/activity/{activity_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the activityActivityIdPut operation.
     * @callback module:api/ActivityApi~activityActivityIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Activity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * put activity
     * @param {Number} activityId 
     * @param {String} activityTitle 
     * @param {String} activitySubTitle 
     * @param {module:api/ActivityApi~activityActivityIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Activity}
     */
    activityActivityIdPut(activityId, activityTitle, activitySubTitle, callback) {
      let postBody = null;
      // verify the required parameter 'activityId' is set
      if (activityId === undefined || activityId === null) {
        throw new Error("Missing the required parameter 'activityId' when calling activityActivityIdPut");
      }
      // verify the required parameter 'activityTitle' is set
      if (activityTitle === undefined || activityTitle === null) {
        throw new Error("Missing the required parameter 'activityTitle' when calling activityActivityIdPut");
      }
      // verify the required parameter 'activitySubTitle' is set
      if (activitySubTitle === undefined || activitySubTitle === null) {
        throw new Error("Missing the required parameter 'activitySubTitle' when calling activityActivityIdPut");
      }

      let pathParams = {
        'activity_id': activityId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'activity_title': activityTitle,
        'activity_sub_title': activitySubTitle
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Activity;
      return this.apiClient.callApi(
        '/activity/{activity_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the activityGet operation.
     * @callback module:api/ActivityApi~activityGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Activity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * put activity
     * @param {module:api/ActivityApi~activityGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Activity}
     */
    activityGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Activity;
      return this.apiClient.callApi(
        '/activity', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the activityPost operation.
     * @callback module:api/ActivityApi~activityPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Activity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * post activity
     * @param {String} activityTitle 
     * @param {String} activitySubTitle 
     * @param {module:api/ActivityApi~activityPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Activity}
     */
    activityPost(activityTitle, activitySubTitle, callback) {
      let postBody = null;
      // verify the required parameter 'activityTitle' is set
      if (activityTitle === undefined || activityTitle === null) {
        throw new Error("Missing the required parameter 'activityTitle' when calling activityPost");
      }
      // verify the required parameter 'activitySubTitle' is set
      if (activitySubTitle === undefined || activitySubTitle === null) {
        throw new Error("Missing the required parameter 'activitySubTitle' when calling activityPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'activity_title': activityTitle,
        'activity_sub_title': activitySubTitle
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = Activity;
      return this.apiClient.callApi(
        '/activity', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
