/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MemberImage from '../model/MemberImage';
import PaperAttachment from '../model/PaperAttachment';

/**
* MemberImage service.
* @module api/MemberImageApi
* @version 1.0.0
*/
export default class MemberImageApi {

    /**
    * Constructs a new MemberImageApi. 
    * @alias module:api/MemberImageApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the memberMemberIdMemberImageMemberImageUuidDelete operation.
     * @callback module:api/MemberImageApi~memberMemberIdMemberImageMemberImageUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaperAttachment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete member image
     * @param {Number} memberId 
     * @param {String} memberImageUuid 
     * @param {module:api/MemberImageApi~memberMemberIdMemberImageMemberImageUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaperAttachment}
     */
    memberMemberIdMemberImageMemberImageUuidDelete(memberId, memberImageUuid, callback) {
      let postBody = null;
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling memberMemberIdMemberImageMemberImageUuidDelete");
      }
      // verify the required parameter 'memberImageUuid' is set
      if (memberImageUuid === undefined || memberImageUuid === null) {
        throw new Error("Missing the required parameter 'memberImageUuid' when calling memberMemberIdMemberImageMemberImageUuidDelete");
      }

      let pathParams = {
        'member_id': memberId,
        'member_image_uuid': memberImageUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PaperAttachment;
      return this.apiClient.callApi(
        '/member/{member_id}/member-image/{member_image_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the memberMemberIdMemberImageMemberImageUuidGet operation.
     * @callback module:api/MemberImageApi~memberMemberIdMemberImageMemberImageUuidGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get member images
     * @param {Number} memberId 
     * @param {String} memberImageUuid 
     * @param {module:api/MemberImageApi~memberMemberIdMemberImageMemberImageUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    memberMemberIdMemberImageMemberImageUuidGet(memberId, memberImageUuid, callback) {
      let postBody = null;
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling memberMemberIdMemberImageMemberImageUuidGet");
      }
      // verify the required parameter 'memberImageUuid' is set
      if (memberImageUuid === undefined || memberImageUuid === null) {
        throw new Error("Missing the required parameter 'memberImageUuid' when calling memberMemberIdMemberImageMemberImageUuidGet");
      }

      let pathParams = {
        'member_id': memberId,
        'member_image_uuid': memberImageUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/member/{member_id}/member-image/{member_image_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the memberMemberIdMemberImagePost operation.
     * @callback module:api/MemberImageApi~memberMemberIdMemberImagePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MemberImage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * post member image
     * @param {Number} memberId 
     * @param {File} image 
     * @param {module:api/MemberImageApi~memberMemberIdMemberImagePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MemberImage}
     */
    memberMemberIdMemberImagePost(memberId, image, callback) {
      let postBody = null;
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling memberMemberIdMemberImagePost");
      }
      // verify the required parameter 'image' is set
      if (image === undefined || image === null) {
        throw new Error("Missing the required parameter 'image' when calling memberMemberIdMemberImagePost");
      }

      let pathParams = {
        'member_id': memberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'image': image
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = MemberImage;
      return this.apiClient.callApi(
        '/member/{member_id}/member-image', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
