/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaperAttachment from '../model/PaperAttachment';

/**
* PaperAttachment service.
* @module api/PaperAttachmentApi
* @version 1.0.0
*/
export default class PaperAttachmentApi {

    /**
    * Constructs a new PaperAttachmentApi. 
    * @alias module:api/PaperAttachmentApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the paperPaperIdPaperAttachmentPaperAttachmentUuidDelete operation.
     * @callback module:api/PaperAttachmentApi~paperPaperIdPaperAttachmentPaperAttachmentUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaperAttachment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete paper attachment
     * @param {Number} paperId 
     * @param {String} paperAttachmentUuid 
     * @param {module:api/PaperAttachmentApi~paperPaperIdPaperAttachmentPaperAttachmentUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaperAttachment}
     */
    paperPaperIdPaperAttachmentPaperAttachmentUuidDelete(paperId, paperAttachmentUuid, callback) {
      let postBody = null;
      // verify the required parameter 'paperId' is set
      if (paperId === undefined || paperId === null) {
        throw new Error("Missing the required parameter 'paperId' when calling paperPaperIdPaperAttachmentPaperAttachmentUuidDelete");
      }
      // verify the required parameter 'paperAttachmentUuid' is set
      if (paperAttachmentUuid === undefined || paperAttachmentUuid === null) {
        throw new Error("Missing the required parameter 'paperAttachmentUuid' when calling paperPaperIdPaperAttachmentPaperAttachmentUuidDelete");
      }

      let pathParams = {
        'paper_id': paperId,
        'paper_attachment_uuid': paperAttachmentUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PaperAttachment;
      return this.apiClient.callApi(
        '/paper/{paper_id}/paper-attachment/{paper_attachment_uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the paperPaperIdPaperAttachmentPaperAttachmentUuidGet operation.
     * @callback module:api/PaperAttachmentApi~paperPaperIdPaperAttachmentPaperAttachmentUuidGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get paper attachment
     * @param {Number} paperId 
     * @param {String} paperAttachmentUuid 
     * @param {module:api/PaperAttachmentApi~paperPaperIdPaperAttachmentPaperAttachmentUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    paperPaperIdPaperAttachmentPaperAttachmentUuidGet(paperId, paperAttachmentUuid, callback) {
      let postBody = null;
      // verify the required parameter 'paperId' is set
      if (paperId === undefined || paperId === null) {
        throw new Error("Missing the required parameter 'paperId' when calling paperPaperIdPaperAttachmentPaperAttachmentUuidGet");
      }
      // verify the required parameter 'paperAttachmentUuid' is set
      if (paperAttachmentUuid === undefined || paperAttachmentUuid === null) {
        throw new Error("Missing the required parameter 'paperAttachmentUuid' when calling paperPaperIdPaperAttachmentPaperAttachmentUuidGet");
      }

      let pathParams = {
        'paper_id': paperId,
        'paper_attachment_uuid': paperAttachmentUuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/paper/{paper_id}/paper-attachment/{paper_attachment_uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the paperPaperIdPaperAttachmentPost operation.
     * @callback module:api/PaperAttachmentApi~paperPaperIdPaperAttachmentPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaperAttachment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * post paper attachment
     * @param {Number} paperId 
     * @param {File} attachment 
     * @param {module:api/PaperAttachmentApi~paperPaperIdPaperAttachmentPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaperAttachment}
     */
    paperPaperIdPaperAttachmentPost(paperId, attachment, callback) {
      let postBody = null;
      // verify the required parameter 'paperId' is set
      if (paperId === undefined || paperId === null) {
        throw new Error("Missing the required parameter 'paperId' when calling paperPaperIdPaperAttachmentPost");
      }
      // verify the required parameter 'attachment' is set
      if (attachment === undefined || attachment === null) {
        throw new Error("Missing the required parameter 'attachment' when calling paperPaperIdPaperAttachmentPost");
      }

      let pathParams = {
        'paper_id': paperId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'attachment': attachment
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = PaperAttachment;
      return this.apiClient.callApi(
        '/paper/{paper_id}/paper-attachment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
