/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.NewsImageResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewsImageResponse', function() {
    it('should create an instance of NewsImageResponse', function() {
      // uncomment below and update the code to test NewsImageResponse
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be.a(WidmBackEnd.NewsImageResponse);
    });

    it('should have the property createdTime (base name: "created_time")', function() {
      // uncomment below and update the code to test the property createdTime
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be();
    });

    it('should have the property imageName (base name: "image_name")', function() {
      // uncomment below and update the code to test the property imageName
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be();
    });

    it('should have the property imagePath (base name: "image_path")', function() {
      // uncomment below and update the code to test the property imagePath
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be();
    });

    it('should have the property imageUuid (base name: "image_uuid")', function() {
      // uncomment below and update the code to test the property imageUuid
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be();
    });

    it('should have the property updatedTime (base name: "updated_time")', function() {
      // uncomment below and update the code to test the property updatedTime
      //var instance = new WidmBackEnd.NewsImageResponse();
      //expect(instance).to.be();
    });

  });

}));
