/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.ProjectsResponseInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectsResponseInner', function() {
    it('should create an instance of ProjectsResponseInner', function() {
      // uncomment below and update the code to test ProjectsResponseInner
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be.a(WidmBackEnd.ProjectsResponseInner);
    });

    it('should have the property createdTime (base name: "created_time")', function() {
      // uncomment below and update the code to test the property createdTime
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property memberImage (base name: "member_image")', function() {
      // uncomment below and update the code to test the property memberImage
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property projectDescription (base name: "project_description")', function() {
      // uncomment below and update the code to test the property projectDescription
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property projectGithub (base name: "project_github")', function() {
      // uncomment below and update the code to test the property projectGithub
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property projectLink (base name: "project_link")', function() {
      // uncomment below and update the code to test the property projectLink
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property projectName (base name: "project_name")', function() {
      // uncomment below and update the code to test the property projectName
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property projectTags (base name: "project_tags")', function() {
      // uncomment below and update the code to test the property projectTags
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property updatedTime (base name: "updated_time")', function() {
      // uncomment below and update the code to test the property updatedTime
      //var instance = new WidmBackEnd.ProjectsResponseInner();
      //expect(instance).to.be();
    });

  });

}));
