/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WidmBackEnd);
  }
}(this, function(expect, WidmBackEnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WidmBackEnd.ProjectTaskInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectTaskInput', function() {
    it('should create an instance of ProjectTaskInput', function() {
      // uncomment below and update the code to test ProjectTaskInput
      //var instance = new WidmBackEnd.ProjectTaskInput();
      //expect(instance).to.be.a(WidmBackEnd.ProjectTaskInput);
    });

    it('should have the property parentId (base name: "parent_id")', function() {
      // uncomment below and update the code to test the property parentId
      //var instance = new WidmBackEnd.ProjectTaskInput();
      //expect(instance).to.be();
    });

    it('should have the property projectTaskContent (base name: "project_task_content")', function() {
      // uncomment below and update the code to test the property projectTaskContent
      //var instance = new WidmBackEnd.ProjectTaskInput();
      //expect(instance).to.be();
    });

    it('should have the property projectTaskSubTitle (base name: "project_task_sub_title")', function() {
      // uncomment below and update the code to test the property projectTaskSubTitle
      //var instance = new WidmBackEnd.ProjectTaskInput();
      //expect(instance).to.be();
    });

    it('should have the property projectTaskTitle (base name: "project_task_title")', function() {
      // uncomment below and update the code to test the property projectTaskTitle
      //var instance = new WidmBackEnd.ProjectTaskInput();
      //expect(instance).to.be();
    });

  });

}));
