/**
 * widm-back-end
 * Nation Central University WIDM LAB back-end API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActivityImageResponse model module.
 * @module model/ActivityImageResponse
 * @version 1.0.0
 */
class ActivityImageResponse {
    /**
     * Constructs a new <code>ActivityImageResponse</code>.
     * @alias module:model/ActivityImageResponse
     */
    constructor() { 
        
        ActivityImageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActivityImageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActivityImageResponse} obj Optional instance to populate.
     * @return {module:model/ActivityImageResponse} The populated <code>ActivityImageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivityImageResponse();

            if (data.hasOwnProperty('activity_id')) {
                obj['activity_id'] = ApiClient.convertToType(data['activity_id'], 'Number');
            }
            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'String');
            }
            if (data.hasOwnProperty('image_name')) {
                obj['image_name'] = ApiClient.convertToType(data['image_name'], 'String');
            }
            if (data.hasOwnProperty('image_uuid')) {
                obj['image_uuid'] = ApiClient.convertToType(data['image_uuid'], 'String');
            }
            if (data.hasOwnProperty('update_time')) {
                obj['update_time'] = ApiClient.convertToType(data['update_time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActivityImageResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActivityImageResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['create_time'] && !(typeof data['create_time'] === 'string' || data['create_time'] instanceof String)) {
            throw new Error("Expected the field `create_time` to be a primitive type in the JSON string but got " + data['create_time']);
        }
        // ensure the json data is a string
        if (data['image_name'] && !(typeof data['image_name'] === 'string' || data['image_name'] instanceof String)) {
            throw new Error("Expected the field `image_name` to be a primitive type in the JSON string but got " + data['image_name']);
        }
        // ensure the json data is a string
        if (data['image_uuid'] && !(typeof data['image_uuid'] === 'string' || data['image_uuid'] instanceof String)) {
            throw new Error("Expected the field `image_uuid` to be a primitive type in the JSON string but got " + data['image_uuid']);
        }
        // ensure the json data is a string
        if (data['update_time'] && !(typeof data['update_time'] === 'string' || data['update_time'] instanceof String)) {
            throw new Error("Expected the field `update_time` to be a primitive type in the JSON string but got " + data['update_time']);
        }

        return true;
    }


}



/**
 * @member {Number} activity_id
 */
ActivityImageResponse.prototype['activity_id'] = undefined;

/**
 * @member {String} create_time
 */
ActivityImageResponse.prototype['create_time'] = undefined;

/**
 * @member {String} image_name
 */
ActivityImageResponse.prototype['image_name'] = undefined;

/**
 * @member {String} image_uuid
 */
ActivityImageResponse.prototype['image_uuid'] = undefined;

/**
 * @member {String} update_time
 */
ActivityImageResponse.prototype['update_time'] = undefined;






export default ActivityImageResponse;

